### ISSUE TITLE
How do we replace hardcoded consent blurb on empirica core with new language?

### ISSUE THREAD

**Issue by isaacgat** [empiricaly/empirica#101]
Right now, the consent blurb is hardcoded into the empirica core. We want to replace it with IRB-approved documentation but we're not sure how to do it. Can you walk us through how to do this? 

@JamesPHoughton

**Comment by npaton** [comment]
This should be fixed in the latest release. Run `empirica upgrade`.

Then you can customize the Consent component in App.jsx:

```
import { Consent } from "@empirica/player";

function MyCustomConsent({ onConsent }) {
    return <Consent onConsent={onConsent} title="Hey" text="please consent" buttonText="do it" />;
}


...

          <GameFrame
            consent={MyCustomConsent}
            introSteps={[Introduction]}
            exitSteps={[ExitSurvey]}
          >
              ...
          </GameFrame>
```

You can also create your own custom consent component of course.

**Comment by kepstein23** [comment]
#107 Having the same problem with this issue as well

**Comment by kepstein23** [comment]
Working on this branch for both issues.

https://github.com/Watts-Lab/deliberation-empirica/tree/kimberly-update-language. 
https://github.com/Watts-Lab/deliberation-empirica/pull/74
