### ISSUE TITLE
Using the ?/playerKey= in the URL when deploying

### ISSUE THREAD

**Issue by kepstein23** [empiricaly/empirica#111]
We've been taking advantage of using a random playerkey for testing by visiting ```localhost:3000/?playerKey={randomPlayerKey}``` Will this still work when the app is deployed. More specifically does visiting ```deployedLink/?playerKey={randomPlayerKey}``` have the same effect?

For context, we're hoping this works so that we can set a baseURL in cypress configs and easily reuse our tests that we've written for testing locally to test deployment by changing the baseURL.

**Comment by npaton** [comment]
I believe this should work.

**Comment by JamesPHoughton** [comment]
Thanks. =) We can close this issue.
