### ISSUE TITLE
Use .jsonl extension for tajriba.json?

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#118]
When we parse the `tajriba.json` file, some parsers trip up because the JSON lines format is not what the parsers are expecting based on the `.json` extension. Would it be a good idea to instead use the extension `.jsonl` suggested by https://jsonlines.org/ to be more explicit?

**Comment by npaton** [comment]
While I agree it would make more sense, I don't think it's a major issue. You need to know it is 1 JSON object per line to start parsing it. But the tooling that can make that distinction by file extension is extremely rare in the first place. At the same time, many tools such `jq` will just accept JSONL natively, whatever the extension. There is also a competing standard http://ndjson.org/. These JSONL-like spec proposals have been vegetating for years.

But I think, more importantly, `tajriba.json` is not considered a public API, so there are no guarantees about its format. The better extension might be no extension or `.empirica`. Even using a single file for the DB or an embedded DB is not guaranteed in the future. The more important format in my mind is the export format. It should try to stay as constant as possible, and we will *try* to do that.

So I don't think we'll change the extension to `.jsonl`, for now at least. I will close this for the time being.

**Comment by JamesPHoughton** [comment]
Works for me. Our only real motivator was that we were parsing the file with cypress to check data entry before we get the data export pipeline built into the tests too. Cypress tries to read the file as JSON and fails. So, once we mature the testing pipeline, even that motivator is irrelevant. =)
