### ISSUE TITLE
Remove auto upgrade from build scripts

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#124]
Trying to build an experiment from last week's version of empirica, I find that the build script tries to upgrade empirica anyways, and fails: (this error message from building https://github.com/JamesPHoughton/empirica/blob/main/test/Dockerfile)
```
> [builder 2/5] RUN empirica create test_experiment:
#11 0.331 ✓  Setup directory
#11 0.382 ✓  Copy project files
#11 48.07 ✓  Install client packages
#11 65.43 ✓  Install server packages
#11 82.15 {"level":"fatal","error":"get current directory: upgrade empirica: upgrade client: yarn upgrade --silent @empirica/player@latest: exit status 1","time":"2022-07-03T17:48:22.128901715Z","message":"empirica: failed to start"}
```

This seems to create a condition where we might develop something working in dev mode with a particular version of empirica, but when we go to package that experiment, it will fetch a different version of empirica. That means we don't really have proper version control, if we can't go back to a previous version and expect it to work as it had previously...

**Comment by npaton** [comment]
This should be fixed.

There is now a version lock file. The checking for upgrade only happens on new projects or explicitly calling `empirica upgrade`
