### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#13]
We need to put some demand on empirica and measure its response and scalability (i.e., simultaneous connections). It seems that the `core` can benefit from some performance optimization as well as we can provide tips and tricks for the `experiments` to improve performance.

**Comment by npaton** [comment]
Maybe https://github.com/alanning/meteor-load-test

**Comment by amaatouq** [comment]
or something like: https://github.com/TurkServer/cooperation-loadtest
