### ISSUE TITLE
Simple Assignment Treatment Factors Undefined

### ISSUE THREAD

**Issue by Alan-Qiao** [empiricaly/empirica#130]
In starting a simple assignment batch, treatment object structure is as follows:
```
{
    desc: '',
    factors: {...},
    name: ''
}
```
However, the expected structure, as is the case for a complete assignment batch, is as follows:
```
{
    treatment: {
        desc: '',
        factors: {...},
        name: ''
    },
    count: 1
}
```

This causes the following issue when trying to access the factors of treatments assigned to a batch.
![console log](https://user-images.githubusercontent.com/33496657/177817369-c45e3d50-f712-4955-9bcb-f1c51de1352e.png)

@jamesphoughton

**Comment by npaton** [comment]
This should be fixed.
