### ISSUE TITLE
Updating Client Side with Async Empirica Callbacks

### ISSUE THREAD

**Issue by Alan-Qiao** [empiricaly/empirica#132]
Hey @npaton 

We want our client side code to wait for an asynchronous callback on the server side to finish, before displaying content, but it never seems to update.

We are using a video conference library which requires an access key to connect a client. The access key is being generated on the server side given a username from the client side.

We trigger the server-side callback by setting `roomName`  parameter on the player object from our [react component](https://github.com/Watts-Lab/deliberation-empirica/blob/798797462f3e6b38e076b23214a0a5209a7196a6/client/src/intro-exit/VideoCheck.jsx#L53-L62). 
```jsx
useEffect(() => {
    console.log("Setting room name to player ID")
    player.set('roomName', round.id);

    return () => {
        player.set('roomName', null) // done with this room, close it
    }
  }, []);
```
The [callback](https://github.com/Watts-Lab/deliberation-empirica/blob/798797462f3e6b38e076b23214a0a5209a7196a6/server/src/callbacks.mjs#L241-L250) then computes the access key using an asynchronous call to a third-party API. The returned key is then set as a parameter on the player object.

```mjs
Empirica.onChange("player", "roomName", async function ({ isNew, player }) {
  if (player.get("roomName")) {
    const access_key = await GetRoomKey(player.get("nickname"), player.get('roomName'));
    player.set('accessKey', access_key);
    console.log(`Set access key for player ${player.participant.identifier} in room ${player.get("roomName")} to ${player.get('accessKey')}`);
  } else {
    player.set('accessKey', null);
    console.log(`Player ${player.participant.identifier} leaving room. Setting access key to null.`);
  }
});
```

However, the [react component](https://github.com/Watts-Lab/deliberation-empirica/blob/798797462f3e6b38e076b23214a0a5209a7196a6/client/src/intro-exit/VideoCheck.jsx#L28-L32) does not seem to receive the update to the player object unless the entire webpage is refreshed.

```jsx
export default function VideoCheck({next}) {
    
    const player = usePlayer()
    const accessKey = player.get("accessKey")
    console.log("Access Key:", accessKey)
    //...
}
```

The following screenshot is from first loading the Video Check Intro Step:
![videoCheck first load](https://user-images.githubusercontent.com/33496657/179573525-3c6c14ad-3985-438c-8bf3-5b2beca1f41f.png)

Notice that in the console log we see that the player object refreshes a few times, but the access key is still `null`. Even if we wait for a long time after the callback is finished, there is no change to the display.

The next screenshot is after refreshing the same webpage:
![VideoCheck Refreshed](https://user-images.githubusercontent.com/33496657/179573751-a89de734-638c-48f7-a333-a85dbca458f0.png)

Notice that in the console log, the access key is now found, and the video component is connecting.

We see the same issue in both the intro stages and the game body. It seems that what is happening is that the change to the player object as a result of the asynchronous callback is not triggering a screen refresh. Is this because we aren't using the callback properly? Or is it that we need to do something else on the client side?

CC: @JamesPHoughton

**Comment by npaton** [comment]
This should be fixed.
