### ISSUE TITLE
usePlayers returns incomplete player list in custom lobby

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#133]
We are trying to build a custom Lobby page that will tell participants how many people have joined, and how many remain. The way we thought to do this is to use the `usePlayers` hook to get the number of players currently in the lobby, as in https://github.com/Watts-Lab/deliberation-empirica/blob/main/client/src/pages/Lobby.jsx#L14
```jsx
const players = usePlayers()
const currentPlayers = players.length;
```
In our testing, however, we find that the returned players object always has length 1, loading only the current player, regardless of how many players are in the lobby.

**Comment by npaton** [comment]
That is a problem in the release you're working with. In the next release, this should be fixed. I will keep this open until it is released.

**Comment by npaton** [comment]
This should be fixed.
