### ISSUE TITLE
`noGames` is rendered even when games are available

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#134]
I have a custom `noGames` page that logs to the console when it is rendered. For example if I have no games, [then I log](https://github.com/Watts-Lab/deliberation-empirica/blob/main/client/src/pages/NoGamesWithSorry.jsx#L11): `No games available pre-login` and if the games all fill and a player cant join a game, [I log](https://github.com/Watts-Lab/deliberation-empirica/blob/main/client/src/pages/NoGamesWithSorry.jsx#L46): `Experiment stoppped in intro screens, stopping payment counter`

I'm noticing that this log is printed even if there are games, whenever the player connects, which makes it seem that before it loads a page, the empirica client is first rendering the noGames page and then rapidly proceeding onto the next screen. On the first load my log reads:

![image](https://user-images.githubusercontent.com/4304478/180654060-ba08790b-e1d3-4e44-a90f-791cc637e4bc.png)
and if I refresh the page during a game:
![image](https://user-images.githubusercontent.com/4304478/180654207-3c4994e2-962d-4f8a-871c-4d7e8551c3bf.png)

This shouldn't be a big deal, as it happens too quickly for the user to notice, but if the `noGame` page has side effects (for example computing payment for participants who do not get to join a game, but have still spent time in the lobby) then the effects can be quite unpredictable. 

Right now, I'm using a timer to delay the side effects for half a second, so that the page can advance without calling the side effects, but still call them if the `noGames` page is displayed on purpose. 
```jsx
useEffect(() => { // runs on first mount
  const timer = setTimeout(() => {
    console.log("Experiment stoppped in intro screens, stopping payment counter")
    ---> sideEffectsGoHere() <----
  }, 500)
  return () => clearTimeout(timer);
}, [])

```

This is a bit brittle, and doesn't strike me as the best solution. Could I be doing something better?

**Comment by npaton** [comment]
That is correct. And it is unwanted behavior. I will keep this open to track it being fixed in the next release.

**Comment by npaton** [comment]
This should be fixed.
