### ISSUE TITLE
How should we handle errors in callbacks

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#135]
At the moment, it seems that if we have an error in a server-side callback, Empirica crashes and stops all games. What would be the best pattern for handling errors there? Should we add a try/catch for each callback? Are there any plans to have V2 isolate each game's callbacks and fail gracefully, so that an error in one game's callbacks doesn't affect the others?

**Comment by npaton** [comment]
Throwing callbacks will not crash the Node.js process on the latest update. But it will not stop the stage/game/batch. It is hard to know what to do when callbacks throw. We'll start by making sure we don't crash everything, then I'd like to hear from the community what they want as options and what's the default behavior.

**Comment by JamesPHoughton** [comment]
My preferred default behavior would be to log and then ignore errors in callbacks. The experimenter could intentionally choose to put a `try...catch` block in the callback if an error there should be addressed in a particular way.

Is there an easy command you could call from a `catch` block in a server-side callback that would stop/advance a stage, round, game, or batch? Also would be nice to be able to throw/reject a batch in `onNewBatch` and have that display an error message on the admin console (ie, for failed batch initialization)

**Comment by npaton** [comment]
In the next update, all callbacks are caught, and a message indicates in which callback it happened.

At this point, we do not change anything about the state of the corresponding game.
