### ISSUE TITLE
No option to go back in intro steps

### ISSUE THREAD

**Issue by benpry** [empiricaly/empirica#136]
Components in the intro steps get a `next` property, which is a function that takes you to the next step. But there is no corresponding `prev` argument for going back. So if I want to provide the option for my participants to go back to a previous page of the instructions, I don't think there is an easy way to do that. In v1, you could do that with the `onPrev` and `hasPrev` properties.

**Comment by npaton** [comment]
It is not currently supported. I will add try to add that back eventually. Meanwhile, to go back, you can try to manually set the `intro` key on the Player like so: `player.set("intro", player.get("intro") - 1)`. You will need to be careful not to allow that value to go below 0 or it will break.
