### ISSUE TITLE
Design and document standard usage strategy for Empirica users

### ISSUE THREAD

**Issue by npaton** [empiricaly/empirica#15]
Experiment designers need to be able to use Empirica core, design their experiment and later update core with the least amount of breakage possible. Currently the idea is to "fork" the repository and pull/merge upstream modifications of the core. This is a viable strategy, but there are others that might also be more practical for the user (e.g. Meteor package). Whichever strategy we end up recommending, we should also document this standard approach for using Empirica.

**Comment by amaatouq** [comment]
Note: classic GitHub “fork” would force the experiment designer to make their repository public, which is less than ideal.

**Comment by amaatouq** [comment]
This is the approach I am working with at the moment (not too bad): https://medium.com/@bilalbayasut/github-how-to-make-a-fork-of-public-repository-private-6ee8cacaf9d3

**Comment by npaton** [comment]
New method: npx create-empirica-app. This can still use more documentation, but it’s working and there’s enough documentation to create a new experiment.
