### ISSUE TITLE
V2 panic: send on closed channel

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#160]
Running empirica serve on build-125, I encountered a "panic" that killed empirica and the container. This was on visiting `localhost:3000` with no query parameters, after having run some previous cypress tests that had errors of their own (a missing resource, not something that should have caused a panic). 

In the server terminal log:
```
empirica-test_1  | panic: send on closed channel
empirica-test_1  | 
empirica-test_1  | goroutine 4112 [running]:
empirica-test_1  | github.com/empiricaly/tajriba/internal/runtime.(*Runtime).pushAttributesForScopedAttributes.func1()
empirica-test_1  |      /go/pkg/mod/github.com/empiricaly/tajriba@v1.0.0-rc.13/internal/runtime/scope.go:426 +0x108
empirica-test_1  | created by github.com/empiricaly/tajriba/internal/runtime.(*Runtime).pushAttributesForScopedAttributes
empirica-test_1  |      /go/pkg/mod/github.com/empiricaly/tajriba@v1.0.0-rc.13/internal/runtime/scope.go:420 +0x31c
deliberation-empirica_empirica-test_1 exited with code 2
```
And in the client console log:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/4304478/193856649-94bed0bd-14f6-440b-8b45-64c6034d3849.png">

**Comment by JamesPHoughton** [comment]
Had this issue again today while testing what happens when you cancel an ongoing game. The test enters a player into a game, then the same tab leaves and goes to the admin console and cancels the game, and then tries to reload the player tab. The panic seems to have occurred either when the game was stopped and when the player returned to their page.

```
empirica_1  | [server] game is now starting with players: 01GESJT3DBBK3CYSAYQD9W0754
empirica_1  | [server] Player 01GESJT3DBBK3CYSAYQD9W0754 disconnected.
empirica_1  | [server] game ending with players: 01GESJT3DBBK3CYSAYQD9W0754
empirica_1  | panic: send on closed channel
empirica_1  | 
empirica_1  | goroutine 7365 [running]:
empirica_1  | github.com/empiricaly/tajriba/internal/runtime.(*Runtime).pushAttributesForScopedAttributes.func1()
empirica_1  |   /go/pkg/mod/github.com/empiricaly/tajriba@v1.0.0-rc.13/internal/runtime/scope.go:426 +0x108
empirica_1  | created by github.com/empiricaly/tajriba/internal/runtime.(*Runtime).pushAttributesForScopedAttributes
empirica_1  |   /go/pkg/mod/github.com/empiricaly/tajriba@v1.0.0-rc.13/internal/runtime/scope.go:420 +0x31c
```

**Comment by npaton** [comment]
This should be fixed. Closing, reopen if you still see this.

**Comment by JamesPHoughton** [comment]
Saw this again this morning when logging into the admin console after a previous test failure canceled a game.

## Environment
build 133, empirica rc.15:

## Server log
```
empirica_1  | panic: send on closed channel
empirica_1  | 
empirica_1  | goroutine 6272 [running]:
empirica_1  | github.com/empiricaly/tajriba/internal/runtime.(*Runtime).pushAttributesForScopedAttributes.func1()
empirica_1  |   /go/pkg/mod/github.com/empiricaly/tajriba@v1.0.0-rc.17/internal/runtime/scope.go:428 +0xf6
empirica_1  | created by github.com/empiricaly/tajriba/internal/runtime.(*Runtime).pushAttributesForScopedAttributes
empirica_1  |   /go/pkg/mod/github.com/empiricaly/tajriba@v1.0.0-rc.17/internal/runtime/scope.go:422 +0x31c
```

## Browser log:
![image](https://user-images.githubusercontent.com/4304478/195058713-006a9648-ef9f-4620-814c-4b491da89287.png)

**Comment by npaton** [comment]
I missed a place... I will push a fix for that tonight or tomorrow morning.
