### ISSUE TITLE
Logo drawing issue on fresh install and new project

### ISSUE THREAD

**Issue by malsobay** [empiricaly/empirica#165]
Hi team, 

I tried following the v2 setup guide step by step, and can spin up the server and create games just fine, but the SVG logo drawn is oversized when I access the player view (see below). I'm on macOS Monterey 12.6 (21G115), and the behavior is the same for all the browsers I've tested: Brave, Chrome, and Safari. 

![image](https://user-images.githubusercontent.com/79336354/195164234-79807ad8-c208-4982-bdee-f4e138e48b80.png)

**Comment by npaton** [comment]
Thanks. I will take a look asap.

**Comment by npaton** [comment]
Can you grab a screenshot of the browser console logs?

**Comment by malsobay** [comment]
![image](https://user-images.githubusercontent.com/79336354/207214254-09aec9d1-15cc-4089-a6c7-34ca510b3f85.png)

**Comment by malsobay** [comment]
@npaton Ok, I can get this working now, but I can't figure out the root cause of the issue. 

All my research projects (including Empirica directories) are in a `research` folder in my main `~/Dropbox (MIT)` folder. I noticed that when I created a new project via `empirica create projectname` in any subfolder of `~/Dropbox (MIT)`, a new empty file `~/Dropbox` would be created. 

So I tried creating a new project outside of the `~/Dropbox (MIT)` directory and it worked.

**Comment by npaton** [comment]
This is a strange behavior indeed. I seems like it could be an issue with having spaces of parens in the path. I will keep this open so we can take a look at it at some point. Thank you very much for the report 🙏

**Comment by npaton** [comment]
I think this was resolved.

**Comment by malsobay** [comment]
Confirming it's been resolved -- thanks!
