### ISSUE TITLE
UnhandledPromiseRejection

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#169]
Saw this bug when starting up a container when the `tajriba.json` already had contents in it from a previous run of the same container:

```
empirica_1  | [server] [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Object]".] {
empirica_1  | [server]   code: 'ERR_UNHANDLED_REJECTION'
empirica_1  | [server] }
empirica_1  | [server] building file list ... 
empirica_1  | [server] 0 files to consider
empirica_1  | [server] 
empirica_1  | [server]   dist/index.js      623.5kb
empirica_1  | [server]   dist/index.js.map    1.7mb
empirica_1  | [server] 
empirica_1  | [server] ⚡ Done in 621ms
```
the `dist/index.js` it refers to is what is built in the `/server` folder.

It's an easy solution to just delete the `tajriba.json` and restart the container, but thought I'd document it here in case anyone else came across the same.

**Comment by npaton** [comment]
It's hard to tell what this is as the error is muted. Restarting Tawon with existing data should simply not throw. If the error is in the core logic, then we need to detect the issue and fix it. If it's in the experiment's code, we should give much better feedback.

We have a ticket to track adding proper error handling (#135). Since this ticket does not point to a clear issue, I will close this issue and prioritize #135 so that if this problem occurs again, it can be reported with actionable details. 🙌

**Comment by JamesPHoughton** [comment]
>Restarting Tawon with existing data should simply not throw.

We have been seeing errors that are resolved by stopping the container, deleting `tajriba.json` and restarting. I wonder if this is because of our container architecture. They may have been tied up with this issue: https://github.com/empiricaly/empirica/issues/155 - If it happens again, I'll see if I can get some better error messages. =)

**Comment by JamesPHoughton** [comment]
This happened again to us again when we had an unhandled error in an `await async` function in our `onGameStart` callback. The error was printed first:
```bash
game is now starting with players: 01GGDB9EJ2YGX00Y2F12ETS6G1
deliberation-empirica-empirica-1 | [server] Player 01GGDB9EJ2YGX00Y2F12ETS6G1 connected.
deliberation-empirica-empirica-1 | [server] 18:29:46.229 INF callbacks: started
deliberation-empirica-empirica-1 | [server] Request to create room 01GGDB96QXC1JJW6HN449E7D8M failed with status 400
deliberation-empirica-empirica-1 | [server] {
deliberation-empirica-empirica-1 | [server]  error: ‘authorization-header-error’,
deliberation-empirica-empirica-1 | [server]  info: ‘invalid authorization header’
deliberation-empirica-empirica-1 | [server] }
deliberation-empirica-empirica-1 | [server] /build/server/src/callbacks.js:53
deliberation-empirica-empirica-1 | [server]  const { name, url } = await CreateRoom(game.id);
deliberation-empirica-empirica-1 | [server]      ^
deliberation-empirica-empirica-1 | [server]
deliberation-empirica-empirica-1 | [server] TypeError: Cannot destructure property ‘name’ of ‘(intermediate value)’ as it is undefined.
```
then after the error message was printed, we saw the unhandled promise rejection error repeat indefinitely:
```
deliberation-empirica-empirica-1 | [server]   at <anonymous> (/build/server/src/callbacks.js:53:11)
deliberation-empirica-empirica-1 | [server]   at processTicksAndRejections (node:internal/process/task_queues:96:5)
deliberation-empirica-empirica-1 | [server] building file list ...
deliberation-empirica-empirica-1 | [server] 0 files to consider
deliberation-empirica-empirica-1 | [server]
deliberation-empirica-empirica-1 | [server]  dist/index.js   623.5kb
deliberation-empirica-empirica-1 | [server]  dist/index.js.map  1.7mb
deliberation-empirica-empirica-1 | [server]
deliberation-empirica-empirica-1 | [server] :zap: Done in 129ms
```
I previously didn't see the error in our code because it scrolled off the page.
