### ISSUE TITLE
Exporting the data

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#17]
The export functionality can be improved:
- From the admin UI, you can choose what games/batches you want to export.
- Export is missing on a lot of data (i.e., the ID inputted by the player such as MTurk ID or email)
- the column `round.data.task` is JSON because that's how we inputted it in `constants.js` .. is there a way that we check if a column is going to be an object/JSON then we flatten it for them? (i.e.,  `round.data.task` becomes multiple columns  `round.data.task.correctAnswer`,  `round.data.task.id`, `round.data.task.path`, `...`

**Comment by npaton** [comment]
Treatment, conditions, lobby config also?

**Comment by amaatouq** [comment]
Now I am thinking that we should export each collection from the database as a flattened csv or json files (they can choose). So, once a user decides which games/batches to export, we downloaded a compressed file that includes:
* players.csv
    * We want to add the durations they spent on the platform (i.e., `introDuration`, `gameDuration`, `outroDuration`)
* playersRounds.csv
    * We want to add the `roundDuration`
* playersStages.csv
    * We want to add the `stageDuration`
* games.csv
    * We want to add the `gameDuration`
... etc

Then it is up to the experimenter to join those tables for analysis.

**Comment by npaton** [comment]
If it's a JSON export, we could also have all this data in one large object. Since it supports embedding, we can structure us for more ease of use with nested objects: `{ game: { startTime: xxx, rounds: [ { number: 1, stages: [ { name: "reponse", ... }, ... ], ... }, ... ], ... }`. Just an idea.

**Comment by amaatouq** [comment]
Yes—makes sense for the json to do it this way.

**Comment by npaton** [comment]
Empirica is now exporting a zip with multiple files, one file per data type (game, player, ...) Data can be re-associated through IDs.
