### ISSUE TITLE
Page refresh

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#170]
Running a built experiment, I experience (as an experiment participant) that after being on a page for between 30 and 90 seconds, the page refreshes. This is most noticeable when the page is playing a video, and the refresh causes the video 
to restart. I'm unsure if this is something I should expect to happen (and work around) or if this is a bug. 

I've seen this behavior in both the intro and game steps. I do not see this behavior when using the dev environment locally.

### Environment:
- FROM ghcr.io/empiricaly/empirica:build-149
- "@empirica/core": "1.0.0-rc.16",
- Deployed on DigitalOcean
- Chrome 105 on a mac

**Comment by npaton** [comment]
There is only one case I can think of where this might happen. If you [enable persistent console logs](https://developer.chrome.com/docs/devtools/console/reference/#persist), when you see the reload, do you see a "spurious provider condition" log?

**Comment by JamesPHoughton** [comment]
These are the logs I get:
![image](https://user-images.githubusercontent.com/4304478/197437207-605b64cf-8a21-4847-87d5-5eecfb7ffc93.png)
This starts with the first time the page was loaded, and my manual log "running fine" is the last entry before the page reload.

**Comment by JamesPHoughton** [comment]
Don't really know how to debug this, but here's a start:

## 1. when does it happen in the experiment?

Happens prior to player registration, in intro steps, and during game.
I log when the component renders with:
```jsx
useEffect(() => {
    console.log("Intro: Consent");
  }, []);
```

- consent
![image](https://user-images.githubusercontent.com/4304478/198042951-cc9e0f64-90d4-4311-8731-c0d9328b5551.png)

- playerId
![image](https://user-images.githubusercontent.com/4304478/198043477-5bc89556-1612-42f7-9dfc-885f847b6631.png)

- Intro check
![image](https://user-images.githubusercontent.com/4304478/198042086-1cc388f4-3b8a-4125-9636-31db19d4e8e0.png)

- enter nickname
![image](https://user-images.githubusercontent.com/4304478/198043876-d2d31ca8-c938-4fa8-9a5a-909dd25159a2.png)

## 2. what environments?
- ✅ On the digitalOcean Server (production build).
- ❌ Not running in the dev container
- ❌ Not from the test container (ie, built with the same dockerfile as production, but running locally)

## 3. what happens on the server
Coincides with disconnect-reconnect from server (timestamps are synchronized below)

![image](https://user-images.githubusercontent.com/4304478/198049917-6ff163c1-4ac8-4e6f-9044-77052eb22aba.png)
![image](https://user-images.githubusercontent.com/4304478/198049962-4b40640e-7b9a-47b9-b762-68e2050542d2.png)

## 4. What type of rerender?
Not a full refresh. On a page refresh we get a different console message. On page refresh, the app reloads and briefly cycles through the "nogames" and "player ID" pages. 
(I log when the app renders with: 
```jsx
  useEffect(() => {
    console.log(`Start: ${process.env.NODE_ENV} environment`);
  }, []);
```
)

![image](https://user-images.githubusercontent.com/4304478/198051035-634daa1a-dcf2-48c4-b063-af2afa605e69.png)

This implies that the rerender is happening below the level of the App object, I believe.

## 5. Network traffic during a re-render looks like this: 
<img width="975" alt="image" src="https://user-images.githubusercontent.com/4304478/198054175-4a57ac7f-524b-42af-8686-aeb67972f190.png">

After another reload:

<img width="978" alt="image" src="https://user-images.githubusercontent.com/4304478/198054352-1f6a97cb-9b1a-4014-a36e-d33c3b4a68e2.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/4304478/198054629-de468a61-228f-4ae7-b103-8cbc5b0c74a4.png">

<img width="672" alt="image" src="https://user-images.githubusercontent.com/4304478/198055168-f3d8e016-275b-4630-99f7-d7a65d6b5b9a.png">

<img width="443" alt="image" src="https://user-images.githubusercontent.com/4304478/198055315-e7b0f665-d8bb-4c9e-aafc-0f2a4e5a6cdf.png">

During a refresh in a video component:
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/4304478/198056439-090e59a0-247a-476b-842d-6f47cf0d172b.png">

## 6. What gets re-rendered?
I added a `DebugComponent` that merely logs that it has been rendered:
```jsx
const DebugComponent = () => {
  useEffect(() => {
    console.log(`Debug Component Rendered`);
  }, []);
  return <></>;
};
```
Within the `EmpiricaParticipant` but outside `EmpiricaContext`:
```jsx
 <EmpiricaParticipant
          url={getURL()}
          ns={playerKey}
          modeFunc={EmpiricaClassic}
        >
          <DebugComponent />
          {isDevelopment && <EmpiricaMenu />}
          <EmpiricaContext
            consent={IRBConsent}
            playerCreate={PlayerIDForm}
            noGames={NoGamesWithSorry}
            lobby={Lobby}
            introSteps={introSteps} // eslint-disable-line react/jsx-no-bind -- empirica requirement
            exitSteps={exitSteps} // eslint-disable-line react/jsx-no-bind -- empirica requirement
          >
            <Game />
          </EmpiricaContext>
        </EmpiricaParticipant>
```

This logs properly during the initial page load, but does not seem to be re-rendered:
![image](https://user-images.githubusercontent.com/4304478/198070021-cd724fce-e135-4498-bc84-5e7939ecce6d.png)

My guess is that something in EmpiricaContext is causing the re-render, and it's associated with possibly losing the webhook connection and re-establishing it.

**Comment by JamesPHoughton** [comment]
I tried to work around this by memorizing the training video component:
```jsx
export const TrainingVideo = React.memo(({ url }) => {
  useEffect(() => {
    console.log(`Playing video from: ${url}`);
  }, []);

```
The component is passed `{url}`, a string with the URL of the video to play. This doesn't change the behavior, possibly because the useEffect player overrides the memorization?

![image](https://user-images.githubusercontent.com/4304478/198077198-ee6e3d46-1ff2-4c8e-b248-b3e49d9b5dac.png)

**Comment by JamesPHoughton** [comment]
Thinking about this some more, it's not merely that react is re-rendering components. That would be normal, and how every change on the page is made. Instead, whatever its doing is triggering a `useEffect` which should only be run on the _first_ render - which is why we see the console logs that come from a `useEffect` with an empty updates list multiple times. A normal re-render wouldn't cause problems.

Is there a name for this? If we were using react classes, I'd say that it was remounting the component, so that `componentDidMount` was being called multiple times. That would indicate that for some reason, the components were being cleared from and reinserted into the DOM tree, instead of just re-rendered. That would also give another explanation for why the memoization above isn't working, because the memoized component is getting taken out of the DOM tree.

**Comment by JamesPHoughton** [comment]
Here's what changes to the DOM look like through the event: (Not sure if there is a better way to capture this)
https://user-images.githubusercontent.com/4304478/198160875-1ff4b11e-2f54-4997-a416-eb4bfe7d2686.mov

Looks as if one root node is being removed and then replaced

**Comment by JamesPHoughton** [comment]
From Nicolas:
> The disconnection issue makes total sense. On disconnection, we “de-render” everything, as we don’t know what the state is anymore. That is the expected behavior. The question becomes, why are we disconnecting. If the interval of disconnections is regular, it will point to a timeout somewhere. It shouldn’t timeout, but I can see a fronting server wanting to do that. Do you have an explicit server like Nginx or apache in front of the app? Or it could be the Digital Ocean’s load balancers. Normally, if the connection is active, most load balancers should keep things open, depending on the configuration. Also, I think we have pings to keep the connection alive, but I will check if that’s the case. If we have pings, it’s the config of the load balancer. If we don’t have pings, we need to add them. I will try to check that today or when we get on a call if I can’t before then


And, yep, it turns out that it reloads after about 100 seconds:
![image](https://user-images.githubusercontent.com/4304478/198164352-c26b5444-3c2d-4782-b9ec-fb3f70bc41bb.png)


It also apparently turns out that our websocket is connecting to CloudFlare? (according to the traffic inspector in chrome dev tools). I don't know why this is, as the app is hosted on DigitalOcean, and I don't particularly understand that relationship. But cloudflare has a 100 second timeout for websockets: https://community.cloudflare.com/t/cloudflare-websocket-timeout/5865. So, that would explain why its timing out, just not what to do about it...

**Comment by JamesPHoughton** [comment]
Thanks to @npaton for build 151, includes a ping-pong that keeps the websocket alive:

![image](https://user-images.githubusercontent.com/4304478/198288858-c8f833e7-5e2a-4ca3-9145-6083983b1a55.png)

This seems to have solved the problem. =)
