### ISSUE TITLE
Deploy Remote Server with http/ws failed

### ISSUE THREAD

**Issue by Pureblackkk** [empiricaly/empirica#172]
Currently, I’m deploying Empirica v2 demo on my remote server. I found it uses https/wss by default in tajriba and related modules, which my server doesn’t support right now. So I wonder if there’s a way to choose using http/ws or https/wss by some settings or config?

**Comment by npaton** [comment]
It looks like we do force https on the admin. It is only on the admin from what I can see, but either way, that is not correct. We will fix that in the next release, within the next week or so.

**Comment by Pureblackkk** [comment]
Thanks, indeed I found this problem when I accessed the admin page.

**Comment by npaton** [comment]
A fix is coming in the next release in the coming days.

**Comment by npaton** [comment]
This should be fixed in the latest release (`empirica upgrade`).

**Comment by Pureblackkk** [comment]
Great, thanks for your efforts!
