### ISSUE TITLE
installation error on linux

### ISSUE THREAD

**Issue by npaton** [empiricaly/empirica#183]
> it seems that when I  do the deploy on my remote server, it failed to download empirica/linux/amd64 file

<img width="686" alt="image (8)" src="https://user-images.githubusercontent.com/9678/200982250-d87708fd-b634-4d0a-8e00-34d2a6e1f13e.png">

**Comment by Pureblackkk** [comment]
Possible reproduce trace here:
1. Download empirica on Linux server before
2. Do rm -rf ~/.local/share/empirica/binaries
3. Curl install again
4. Input any cmd of empirica at the root of the folder where '.empirica' is created
5. The error above showed up

I try to make a new folder and download it again and it works, it might relate to the .empirica for cache or something else which is not compatible.

**Comment by npaton** [comment]
I believe this should be fixed. You will need to reinstall. Since you have installed before the final release, you might need to cleanup the older installation. You can find direction for doing that here: https://docs.empirica.ly/getting-started/setup#pre-release-cleanup
