### ISSUE TITLE
NewPlayer form re-renders whenever client refreshes

### ISSUE THREAD

**Issue by srflet** [empiricaly/empirica#191]
Adding a custom NewPlayer form to the EmpiricaContext prop PlayerCreate causes the NewPlayer form to be re-rendered whenever the client is refreshed. This happens after a client has been assigned to a game. 

App component with EmpiricaContext:
![image](https://user-images.githubusercontent.com/43952639/205661293-d248ff87-3153-46aa-a5eb-0f4fde4678b8.png)

NewPlayer form with logging to demonstrate re-renders:
![image](https://user-images.githubusercontent.com/43952639/205661191-5483fc01-137e-4c02-90a7-c11ca31cc96a.png)

Console logs after refreshing from stage of a game:
![image](https://user-images.githubusercontent.com/43952639/205659775-af33f4a2-9d20-454e-a515-25062a7afe1a.png)

Things to note:
This is an app with manual assignment of players to games. After the player is created, they are prompted to click "Join" to join a game. In callbacks this checks to see if a game exists in the batch and assigns them to it, and if not create a game, add a round and stage, and then assign the player and start the game. 
![image](https://user-images.githubusercontent.com/43952639/205660889-01a35f2c-9310-4879-9fcb-5eb544f660df.png)

**Comment by npaton** [comment]
I believe this was fixed in a previous release.
