### ISSUE TITLE
Freeze treatments, conditions, condition values and lobby configuration into each game

### ISSUE THREAD

**Issue by npaton** [empiricaly/empirica#20]
We want to be able to edit and delete configurations (treatments, conditions, condition values and lobby configuration, etc.) but we don't want to break games that have already ran. So we should copy (freeze) all the configuration into each game.

**Comment by npaton** [comment]
Also add deletion of all these configuration objects to the UI.

**Comment by joshua-a-becker** [comment]
Copying configurations into each game is a good idea for stability.

For experimenters, it's still a good idea never to delete anything.

So one supplementary strategy is---never delete, only archive.  This can be done by giving each entry an additional binary flag.   When flagged, it would be hidden from view in the admin panel.  Eg, when creating a new batch, an archived treatment isn't visible.  So, archiving doesn't change the underlying data structure, just what is visible to the admin user.   But then a "view archived" option would allow you to view old entries; the archive flag would, from this view, un-archive.

Thanks for this amazing platform :)   :)   :)

**Comment by npaton** [comment]
Agreed, that would work as well. I can't remember why I didn't want to go this route initially. I might have been thinking of trying to keep conditions/treatments unique, and if you delete (archive/hide in reality), then someone creating an equivalent treatment gets an error message later that this condition/treatment already exists, but they can't immediately see it because it's hidden, it might add confusion. For that specific issue, could always put message, "that treatment exists and was deleted". Or there might have been a more fundamental issue, I can't remember.

But as I work on this, I'll see if this way (add deleteAt:timestamps and deletedBy:userId fields => we might as well keep the info on who did it and when this was done) will actually work. If it does, there is no real need to copy the info over into the games, having a reference to the objects in the game is enough. If we don't have referential integrity, everything is broken, so we must assume as much and work to maintain it.

By the way @joshua-a-becker welcome on board, glad you like the platform and to have you with us!

**Comment by joshua-a-becker** [comment]
a few notes...

1. from my perspective, there's no reason to prohibit identical treatments from being created.
2. what should be unique and currently isn't enforced:  treatment names.  i accidentally created two treatments with the same name but different conditions,  and then when creating a game, had no way to distinguish.  (alternatively:  show some unique index in the games panel)
3.  copying data over is necessary for the 'edit' feature, even if not for the 'delete' feature.

BTW @npaton thanks for this amazing product!  i'm currently building an experiment with it and will be doing more soon

**Comment by npaton** [comment]
> 1. from my perspective, there's no reason to prohibit identical treatments from being created.

Fair enough. What is the value of being allowed to do this?

> 2. what should be unique and currently isn't enforced: treatment names. i accidentally created two treatments with the same name but different conditions, and then when creating a game, had no way to distinguish. (alternatively: show some unique index in the games panel)

Fair as well. Though this kind of confusion could also be an issue with multiple treatments with identical conditions: where did half of my games go for this treatment? Oh, right, there under this other identical treatment.

I'm thinking we should enforce both a unique set of conditions and unique name.

> 3. copying data over is necessary for the 'edit' feature, even if not for the 'delete' feature.

For editing, only the name can be edited. As long as the conditions do not change, I don't see why you couldn't fix a typo after a game, or decide your naming scheme needs an overhaul. It does not change the game parameters. And not copying treatments/conditions over allows for this kind of fixing after the fact.

---

At this, point, I am still inclined to:
- not copy treatments/conditions over
- enforce unique treatment names
- keep enforcing unique sets of conditions
- add an archiving feature (no deletion)

What do you think?

One thing I'd eventually like to do as well is to be able to have in the UI a link on treatments to all the associated games, same for conditions.

**Comment by npaton** [comment]
I have added archiving on Treatments and Lobby configurations, editing of treatment names, and unique names for treatments and lobby configurations.

**Comment by joshua-a-becker** [comment]
This really helps to streamline my process.

Any plans to add archiving to batches?

**Comment by amaatouq** [comment]
already implemented. Make sure to pull the latest changes from the master. Reset the app `meteor reset` then `meteor npm install` and you'll have it :)

**Comment by joshua-a-becker** [comment]
Not sure if this was an intentional design decision---archived *treatments* are still available in the "New Batch" dialogue.

**Comment by npaton** [comment]
That was not the intention, thank you for catching that. It should be fixed now. 🍂
