### ISSUE TITLE
Timer not showing when player joins a game

### ISSUE THREAD

**Issue by zablaveki** [empiricaly/empirica#207]
Note: The bug is not constantly reproduced.

### Steps  to reproduce:

1. Login to admin, create a batch with 2 players and start the game
<img width="1642" alt="Знімок екрана 2023-01-09 о 22 07 07" src="https://user-images.githubusercontent.com/118141246/211398542-95ab385e-bd2a-4d04-b4c9-323d7c2b7420.png">

2. Login as player 1 and go the the first round. Login as player 2 and join the first round:

<img width="875" alt="Знімок екрана 2023-01-09 о 22 08 08" src="https://user-images.githubusercontent.com/118141246/211399194-097c39f9-354a-4e52-962d-9249e8623688.png">

<img width="1010" alt="Знімок екрана 2023-01-09 о 22 08 14" src="https://user-images.githubusercontent.com/118141246/211398659-4bc05b33-d735-4243-baa5-f26af18613c0.png">

## Expected behavior: 
Player 1 and player 2 see timer counting down from 5 minutes

## Actual behavior:
Player 1 sees --:-- instead of the timer.

**Note:** when player 1 reloads the page, the timer usually shows as expected

**Comment by JamesPHoughton** [comment]
Related to https://github.com/empiricaly/empirica/issues/129 - I'm still seeing this with version `empirica:build-154`, `"@empirica/core": "1.0.0-rc.23"`, curious to know if it's fixed in `v1.0.0`

**Comment by npaton** [comment]
Not yet, we're still looking into it. Soon hopefully.

**Comment by JamesPHoughton** [comment]
Just want to see if there's an update here - I'm using stage timers to show participants different pieces of text and different times, so this may be blocking for our experiments coming up. Anything I can do to help? 

As always, super grateful for you guys @npaton, @zablaveki. 🤩

**Comment by npaton** [comment]
Sorry, yes, it's at the top of our list. I tried to reproduce it last week, and I was having a hard time. I believe @zablaveki has found a way to reproduce it reliably, so getting closer. Hopefully this week. 🙏

**Comment by zablaveki** [comment]
The fix is released in `v1.1.2`
