### ISSUE TITLE
player.filter(callback)

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#215]
Is it possible to "filter" player data similar to how you might with a js array? Pass a callback that lets us do something like:
```js
player.set("answer_1", "Fred");
player.set("answer_2", "George");
player.set("answer_3", "Ron");

const answers = player.filter(item => item.key.includes("answer"))  // something like this? player.filterAttributes()?
answers // {"answer_1": "Fred", "answer_2": "George", "answer_3": "Ron"}
```

I could always have an object that I update with each of the values, but I worry that as the object gets large, this will negatively affect performance...

**Comment by npaton** [comment]
Ah, yes, that would be very useful. I think it's possible to get the list of attributes, but it's not a published API. I think the API should be to return an array or Set or Map, and then you can use any of the common iteratable functions (filter, every, some...)

**Comment by JamesPHoughton** [comment]
I've been assembling a list of keys from the set of nested Maps in the player attributes:
```js
function getKeys(player) {
  const scopes = Array.from(player.attributes.attrs.values());
  const keys = scopes.map((item) => Array.from(item.keys())).flat();
  return keys;
}

function filterByKey(player, filter) {
  const allKeys = getKeys(player);
  const filteredKeys = allKeys.filter(filter);
  const entries = filteredKeys.map((key) => [key, player.get(key)]);
  return Object.fromEntries(entries);
}

const surveys = filterByKey(player, (key) => key.startsWith("survey_"));
```
although I notice a lot of duplicate entries in the nested Maps, which seem to all be empirica-related objects, not things that I've set. I assume it's ok to just treat them as redundant?

**Comment by npaton** [comment]
I think `.attributes.attrs` returns all attributes across all objects, not just attributes for the current object (player).

**Comment by npaton** [comment]
You can use `player.inspect()` which returns an object containing all the attributes of the object. E.g.,  `{"thing": 42}`.

```js
Object.fromEntries(Object.entries(player.inspect()).filter(([key, value]) => key.startsWith("hey")));

// If you do this a lot
function filter(empiricaObject, filter) {
    return Object.fromEntries(Object.entries(empiricaObject.inspect()).filter(filter));
}

filter(player, ([key, value]) => key.startsWith("hey"));
```
