### ISSUE TITLE
Handling stage submission with player dropout

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#219]
Let's say I have a game with lots of stages that are generally manually advanced, _i.e._ when all players "submit", they are then able to proceed to the next page.

If a player drops out of the game, and is no longer connected, the current behavior is that even if all other connected players "submit" the stage, the stage will not advance until the timer finishes, because there is still one player position that hasn't been submitted.

Is there a way to check for player disconnection and advance the stage when all connected players are ready? This probably wants to include some lag to prevent accidental advancing if a player disconnects and reconnects immediately. (Maybe a 10-second wait?)

**Comment by npaton** [comment]
Currently I know we check for exited players but maybe not disconnected players. We need to add this. 👍

**Comment by zablaveki** [comment]
Released in `v1.1.2`
