### ISSUE TITLE
Display custom batch json in admin console

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#243]
Currently, if you create a batch with a custom JSON file, in the batches tab you don't have any information about the batch other than it is custom:

![image](https://user-images.githubusercontent.com/4304478/218789490-2dfd5609-14a1-4986-ad94-428a814ccda2.png)

It would be helpful to be able to show the JSON that was used to create the batch, similar to:

<img width="972" alt="image" src="https://user-images.githubusercontent.com/4304478/218790575-949b0019-e8aa-44f7-a681-71a45496b4a6.png">

**Comment by zablaveki** [comment]
Release in `v1.1.2`
