### ISSUE TITLE
server NODE_ENV stuck thinking it's in 'production'

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#253]
My server always seems to think it's in production mode, according to:

```js
// in callback.js
console.log(`Node Environment: ${process.env.NODE_ENV}`);  // yields "production"
```

This seems to be because the build script hardcodes it that way:
```json
"scripts": {
    "build": "rsync -aP --exclude=node_modules --exclude=*.js -m src/* dist/ && esbuild src/index.js --platform=node --define:process.env.NODE_ENV='\"production\"' --bundle --minify --outfile=dist/index.js --sourcemap",
    "dev": "npm run build && node --trace-warnings --enable-source-maps dist/index.js",
    "serve": "node --trace-warnings --enable-source-maps index.js"
  }
```

is this on purpose and/or needed? The `process.env.NODE_ENV` variable responds as expected client side...

**Comment by npaton** [comment]
'build' is normally intended to make a production build. In development, 'dev' should be used. That being said, there should be a way to make the build with production and still let the var be changed at runtime.

**Comment by JamesPHoughton** [comment]
I haven't updated those lines in 6 months (https://github.com/Watts-Lab/deliberation-empirica/blame/main/server/package.json) - I'm trying to remember if we wrote it that way as a workaround for something. I'm not really sure what everything in this set of scripts does. Could I just create a `build:dev` in addition to the existing `build` script line?

**Comment by npaton** [comment]
I think it's there from the start with production locked in. A `build:dev` script would work for now 👍

**Comment by npaton** [comment]
`build` is meant for production, so I don't want to change it. I think the case for wanting a production build, without production optimizations is fairly rare, so I'm not adding it just now for every one. Of course, you can add it to your project if you need it. Feel free to reopen if you have more info about this. 👍
