### ISSUE TITLE
Build numbers have been reset

### ISSUE THREAD

**Issue by npaton** [empiricaly/empirica#259]
@JamesPHoughton noticed our build numbers have gone backwards. He uses build numbers to reference Docker container image builds. We could add an offset to our current build number, but that would make the build number not mean much (hard to find the build that actually made the image). I think we might just leave it as is, and we will overwrite old images. Since no-one else is using the Docker containers, I don't think it will immediately be a problem, though we might want to remove the old images. Or maybe we change the tag to be `build-num-${number}`, so there is no conflict.

We should also add other tags to the container images: `version`, maybe a "timestamp" one. I don't know. TBD.

**Comment by JamesPHoughton** [comment]
Thanks, any of those work for me. =)

**Comment by npaton** [comment]
I'm fine not using the build number. The main reason for it is to be able to go and find the incriminating build. So it's nice as an extra piece of info for cases like the `empirica version` output. But for tagging, it's not great.

Calver seems to be for cut versions, since they do not include time in their "spec". In this case, we might have multiple builds in a day, so it's no ideal to overwrite builds.

E.g. We're working on fixing an issue, we're not releasing. The user we're trying to fix the issue for should be able to target a specific build. Say build 123 kinda works, build 124 is broken. Neither are published builds. While we're still working on the issue, the user should be able to target 123, even if was built the same day as 124.

Maybe calver but with time (minute precision should be enough)?

**Comment by zablaveki** [comment]
Tags example:

Release build tags:
v1.0.4
v1.0.5

Test build tags:
23.03.10_1640

**Comment by zablaveki** [comment]
Changed the tagging of builds in https://github.com/empiricaly/empirica/pull/268
