### ISSUE TITLE
`onRoundStart` is missing `players` data at round 0

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#26]
For instance
```javascript
export const onRoundStart = (game, round, players) => {
  console.log("Round ", round.index, " started");
  console.log("players are ", players);
};
```
will print an empty list of player `[]` when `round.index` is 0 and then it will populate the `players` fro round 1!

**Comment by amaatouq** [comment]
same for `game` data. It seems that everything is missing at `round.index` equal to `0`

**Comment by npaton** [comment]
This should be fixed, needs testing.

**Comment by amaatouq** [comment]
it works.

**Comment by amaatouq** [comment]
now `players` exist in the first round (i.e., index 0) but `game` is `undefined`. 

The same with the undefined game in `onGameStart`
