### ISSUE TITLE
Using player.set("key", "value") in intro steps hard reloads component

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#263]
I have a component structurally similar to the following:

```jsx
import React, { useState } from "react";
import { usePlayer } from "@empirica/core/player/classic/react";
import { Button } from "myButtonComponent";

export function myComponent() {
  const player = usePlayer();
  const [myStatefulValue, setMyStatefullValue] = useState("default");

  const updatePlayerObject = () => {
    setMyStatefulValue("notDefault");
    player.set("newKey", "newValue");
  };

  return (
    <div>
       <p>My Stateful Value: {myStatefulValue}</p>
       <Button onClick={updatePlayerObject} />
    </div>
  );
}
```

If I use this component in the main body of the game, then when I click the button, the player object gets updated, and the page displays the expected "My Stateful Value: notDefault".

However, if I use the same component in an intro stage (where I have access to the player object) the `player.set()` method sets the value properly on the player object, but the whole component reloads (if that's the right term), clearing the `useState`, so that now the page displays "My Stateful Value: default". (In my actual component, it also resets radioButtons, clears textAreas, etc.).

Is this something I can work around or fix?

**Comment by JamesPHoughton** [comment]
Yes, I'm seeing it when I load a [`Prompt`](https://github.com/Watts-Lab/deliberation-empirica/blob/main/client/src/elements/Prompt.jsx) component inside a [`GenericIntroStep`](https://github.com/Watts-Lab/deliberation-empirica/blob/main/client/src/intro-exit/GenericIntroStep.jsx) component. The `GenericIntroStep` takes a list of dictionaries, and uses the fields of each dictionary to select a component and parameterize it. The `GenericIntroStep`
is created in the [`App/introSteps()` function](https://github.com/Watts-Lab/deliberation-empirica/blob/main/client/src/App.jsx#L46-L51).

It looks like the introSteps function gets run every time the `player` object is modified. My knowledge of react object persistence is incomplete, but I could guess that could also be where the breakdown is happening...

**Comment by JamesPHoughton** [comment]
Turns out it still breaks if I put the `Prompt` component on its own (ie, outside of `GenericIntroStep`):

```js
// reloads everything on player.set(...)
  function introSteps({ player }) {
    const steps = [
      ({ next }) =>
        Prompt({
          file: "projects/example/multipleChoiceWizards.md",
          saveKey: "testsave",
        }),
    ];
    return steps;
  }
```
If I take it out of the arrow function and give it a proper function, it's better behaved:
```js
// does not reload on player.set(...), maintains useState in components
  function promptOnlyIntroStep({ next }) {
    return Prompt({
      file: "projects/example/multipleChoiceWizards.md",
      saveKey: "testsave",
    });
  }

  function introSteps({ player }) {
    const steps = [promptOnlyIntroStep];
    return steps;
  }
```

It doesn't seem to be just arrow functions that are creating the problem, as I have the same issue with a closure:
```jsx
// reloads everything on player.set(...)
  function introStepFactory({ name, elements }) {
    function introStep({ next }) {
      return GenericIntroStep({ name, elements, next });
    }
    return introStep;
  }

  function introSteps({ player }) {
    const elements = [{ file: "projects/example/multipleChoice.md", type: "prompt" }];
    const name = "testGIS";
    const steps = [introStepFactory({ name, elements })];

    return steps;
  }
```

**Comment by JamesPHoughton** [comment]
Tried stashing the intro steps in a `useState` at the app level:
``` jsx
export default function App() {
  const [introStepsKeeper, setIntroStepsKeeper] = useState();

  function introSteps({ player }) {
    if (introStepsKeeper) return introStepsKeeper;

    console.log("Running introSteps");
    const steps = [];
    const introSequence = player.get("introSequence");

    introSequence?.introSteps.forEach((step) => {
      const { name, elements } = step;
      console.log("elements", elements);
      const introStep = ({ next }) =>
        GenericIntroStep({ name, elements, next });
      steps.push(introStep);
    });

    setIntroStepsKeeper(steps);
    return steps;
  }
```
but had the error:
![image](https://user-images.githubusercontent.com/4304478/224068529-34bba36e-beb4-4ead-9242-c3fb669d67cc.png)

which I guess makes sense...

**Comment by JamesPHoughton** [comment]
Would it be hard to make it so that the `introSteps` and `exitSteps` could accept extra arguments for the step components? Not sure exactly what syntax would be best, something like:

```jsx
function MyParameterizableComponent({next, param1, param2}) {
  // something that depends on param1 and param2
}

function introSteps({player}) {
  return [
    (MyParameterizableComponent, {param1: "first", param2: "initial"}), 
    (MyParameterizableComponent, {param1: "second", param2: "secondary"})
  ] 
}
```

**Comment by npaton** [comment]
I am not seeing this issue with the following test setup.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/9678/232271234-24427ed0-1fbf-4ae1-8b57-9d386299b874.png">
<img width="475" alt="image" src="https://user-images.githubusercontent.com/9678/232271308-96b69ea1-f43e-489b-a609-acd329c6bf84.png">
<img width="486" alt="image" src="https://user-images.githubusercontent.com/9678/232271351-f431ec37-5c99-4228-a6d5-acfc4539fa2c.png">

```js
import { usePlayer } from "@empirica/core/player/classic/react";
import React, { useEffect, useState } from "react";
import { Button } from "../components/Button";

export function Introduction({ next }) {
  const player = usePlayer();
  const [myStatefulValue, setMyStatefullValue] = useState("default");

  const updatePlayerObject = () => {
    setMyStatefullValue("notDefault");
    player.set("someValue", Math.random());
  };

  useEffect(() => {
    console.log("Initial render");
  }, []);

  console.log("Rerendering");

  return (
    <div className="m-10">
      <p>My Stateful Value: {myStatefulValue}</p>
      <p>Player value: {player.get("someValue")}</p>
      <Button handleClick={updatePlayerObject}>Button</Button>
    </div>
  );
}
```

<img width="714" alt="image" src="https://user-images.githubusercontent.com/9678/232271594-fa4a4c95-c695-4112-9939-3f3e87ab0a05.png">

This demonstrates that updating `player` does not force reload the component, even if we're using a function to define the intro steps. That being said, I am running on a newer release that might have other issues fixed (there were some improvements to initialization). When I release the next version (today hopefully), please try again, and if it's still happening, I will look into your setup specifically (using an indirection with `GenericIntroStep`).

**Comment by JamesPHoughton** [comment]
Must be something we're doing then. I've updated empirica in this branch: https://github.com/Watts-Lab/deliberation-empirica/tree/james-prompts-in-intro, and the error is raised in the following test:
https://cloud.cypress.io/projects/htzagd/runs/906/test-results/57f98f4a-3d86-4fcd-b843-ee56df9a02da

I'll see if I can replicate in a minimal example.

**Comment by JamesPHoughton** [comment]
Here's a minimally replicating example: https://github.com/JamesPHoughton/empirica-bug-parameterized-intro

walkthrough video:
https://user-images.githubusercontent.com/4304478/235748679-a42a7b54-78e0-4e6b-a2be-336bbb30a02e.mov

**Comment by npaton** [comment]
I pushed a fix for this in the latest release. Try to `empirica upgrade` inside your project.
