### ISSUE TITLE
How should I set a global when server starts?

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#264]
When I start the server, I'd like to be able to fetch a resource and set it to a global object that can be accessed by players. Currently, I'm doing this in the batch creation callback:

``` js
Empirica.on("batch", async (ctx, { batch }) => {
  // Batch created

  if (!ctx.globals.get("resource")) {
    const resource = await getResource();
    ctx.globals.set("resource", resource);
  }
}
```
Is there a better solution?

**Comment by npaton** [comment]
You can use on start.

```js
  Empirica.on("start", function (ctx) {
    // ...
  });
```

This is untested in an experiment, but it used internally so there's no reason it wouldn't work. Let me know how it goes.

**Comment by JamesPHoughton** [comment]
This works great! 

Interestingly, if I log something here, it doesn't display when the server launches the first time, but does when the server is restarted. That may be due to our docker setup, though, hard to say. It definitely fires the callback - if I save something to globals here, I can retrieve it later as expected.

**Comment by npaton** [comment]
Great. It should. Let us know if it doesn't.
