### ISSUE TITLE
Server error on changes to `callbacks.js`

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Changes to callbacks.js when a game is running cause a server error. Its not something that is likely to happen in production, but happens all the time in dev. The server spits out a console error and the experiment freezes in the browser.

If you stop and restart the server, nothing happens (ie, no page is available at localhost:3000, no console logs) unless you first delete `tajriba.json`, after which there is no error.

### Steps To Reproduce

1. Create a brand new experiment, open it in an editor, and start the server
```bash
> empirica create test
> cd test
> code .
> empirica
```
2. Start a 1 player game, and walk through the intro stages and first stage of the game
3. Make a small change to `callbacks.js`, that should have no effect on the actual operation of the code
4. Error appears in the console pretty much immediately.

Here's a screen recording:
https://user-images.githubusercontent.com/4304478/228412316-8098de52-ca00-4877-b333-01a5a10d4e90.mov

### Empirica Version

```text
(base) jamesphoughton@Jamess-MBP-3 experiments % empirica version
Version: v1.1.2
SHA:     5f44fbc
Build:   82
Branch:  main
Time:    2023-03-06T09:23:18Z
```

### What OS are you seeing the problem on?

macOS

### What browser are you seeing the problem on?

Chrome

### Relevant log output

```shell
[server] 22:28:28.416 WRN failed load: [GraphQL] transition step: invalid state
[server] [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Object]".] {
[server]   code: 'ERR_UNHANDLED_REJECTION'
[server] }
[server] building file list ... 
[server] 0 files to consider
[server] 
[server] sent 29 bytes  received 20 bytes  98.00 bytes/sec
[server] total size is 0  speedup is 0.00
[server] 
[server]   dist/index.js      737.2kb
[server]   dist/index.js.map    2.9mb
[server] 
[server] ⚡ Done in 52ms
```

### Anything else?

[tajriba.json.txt](https://github.com/empiricaly/empirica/files/11095940/tajriba.json.txt) after the error and attempting to restart the server

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
Yeah, that's not how it should work. I'll look into it.

**Comment by npaton** [comment]
This should have improved with the latest version. Still tracking down some cases.

**Comment by npaton** [comment]
I think this is fixed.
