### ISSUE TITLE
Add inspect method for popular game concepts

### ISSUE THREAD

**Issue by shawnzam** [empiricaly/empirica#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

When `console.log(game)` for `game` and similar Empirica objects, the output is not very helpful. Can an `inspect()`, or similar, method be added to make inspecting these objects more useful. A recursive list of keys and values would likely be enough.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
There is an `.inspect()` method on the main objects (`game`, `player`, `stage`…) that returns an object containing all the attributes on the object:

```
console.log(game.inspect())
```
