### ISSUE TITLE
Batch button has incorrect label on restart

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If the Empirica server restarts after a batch is either started or started and ended, the button in the admin console displays "start", when it should reflect the fact that the batch has already begun or has been closed altogether. 

### Before server restart
![image](https://user-images.githubusercontent.com/4304478/231255793-44c01110-3744-4ffb-93c1-38df0c6c8bf6.png)

### After server restart
![image](https://user-images.githubusercontent.com/4304478/231255038-da0b707b-dae1-4c3d-b276-d73be0d70b42.png)

### Steps To Reproduce

1. Create a batch with the demo experiment and start it
2. Kill the empirica process and restart it (without touching tajriba.json)
3. View the admin console

### Empirica Version

```text
Version: v1.1.2
SHA:     5f44fbc
Build:   82
Branch:  main
Time:    2023-03-06T09:23:18Z

Client:  1.1.2
Server:  1.1.2
```

### What OS are you seeing the problem on?

macOS

### What browser are you seeing the problem on?

Chrome

### Demo video of running batch

https://user-images.githubusercontent.com/4304478/231254252-f3539150-54e4-47ec-a94e-1cb0a205a0e7.mov

### Demo video of closed batch

https://user-images.githubusercontent.com/4304478/231256074-c959ed0b-16c4-4166-b994-949c56e60fea.mov

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
This should be fixed in the latest release.
