### ISSUE TITLE
Use `player.stage.set()` to launch a callback

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'd like to trigger a callback when a value is set to `player.stage`.

### Describe the solution you'd like

If I run the following code in my client:
```js
player.stage.set(“result”, {data})
```

I'd like to do something like:
```js
Empirica.on("player.stage", "result", (ctx, { player, result }) => {
  console.log("player.stage callback", result);
}
```

### Describe alternatives you've considered

A workaround is to do something like:

```js
// client
const resultName = `result_${stage.id}`
player.set(resultName, resultObj)
player.set("stageResultReady", resultName)

// server
Empirica.on("player", "stageResultReady, (_, { player, stageResultReady }) => {
  if (!stageResultReady) return;
  const resultObj = player.get(stageResultReady);
  // deal with the resultObj
  player.set("stageResultReady", false)

```

### Teachability, Documentation, Adoption, Migration Strategy

be able to set values to `player.stage` (and possibly other nested objects?) and trigger callbacks as necessary.

cc: @kepstein23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
It's on `playerStage`. `player.stage` might have been more elegant…

```js
Empirica.on("playerStage", "result", (ctx, { player, result }) => {
  console.log("player.stage callback", result);
}
```

Let me know if that works. 👍
