### ISSUE TITLE
using option `tajriba.store.file` in `empirica.toml` causes problems with callBackSessionToken

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If I set 
```toml
# empirica.toml
tajriba.store.file = "/data/tajriba.json"
```
then on deploy I get:
```
{"level":"info","time":"2023-04-25T19:02:45.26361755Z","message":"serve: server started"}
{"level":"info","time":"2023-04-25T19:02:45.385397383Z","message":"empirica: server started"}
19:02:49.201 ERR token: write token file ENOENT: no such file or directory, open '/.empirica/local/callBackSessionToken'
```

I'm guessing that this is because whatever script creates `/.emprica/local/tajriba.json` is doing the work of directory creation for the callBackSessionToken.

### Empirica Version

```text
SHA:     47c52f3
Build:   249
Branch:  bugfix-merge-build-release
Time:    2023-02-08T09:59:15Z

Client:  1.0.6 ->  -> 
Server:  1.0.6 -> 1.0.0-rc.23 -> 1.0.0-rc.23
```

### Anything else?

Manually creating the folder solves the problem
```bash
mkdir /.empirica
mkdir /.empirica/local
```

### Code of Conduct

- [X] #297

**Comment by npaton** [comment]
Should be fixed in the latest release. 👍
