### ISSUE TITLE
Adding infinite timer

### ISSUE THREAD

**Issue by Yichabod** [empiricaly/empirica#3]
It would be great to add a clear option for an infinite timer and also to skip the default page.

**Comment by npaton** [comment]
Running locally, when you click on "Start" a batch, if you hold command (mac) or ctrl (window), the stage timers will be set to a large value (1h I think) and it will skip the intro steps.

We want to eventually make this an explicit button, so it'd more discoverable. I'm keeping this ticket open so we remember to address this.
