### ISSUE TITLE
Cannot `empirica export` on server

### ISSUE THREAD

**Issue by aliciamchen** [empiricaly/empirica#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I deployed my experiment to a server using the instructions [here](https://docs.empirica.ly/guides/deploying-my-experiment). I am unable to `empirica export` even though the package `@empirica/core` in `.empirica/local/export` exists (and `.empirica/local/tajriba.json` exists too)

This is the message I get: 
```
empirica export
Setting up export environment...
Volta error: Could not locate the package '@empirica/core'

Please ensure it is available by running `npm link` in its source directory.
Error details written to /root/.local/share/empirica/volta/log/volta-error-2023-06-10_22_10_26.178.log
14:30:24.788 FTL empirica: failed to start error="npm link @empirica/core: exit status 126"
14:30:24.791 FTL empirica: failed to start error="server: empirica npm link @empirica/core: exit status 1"
```

This is the message in `/root/.local/share/empirica/volta/log/volta-error-2023-06-10_22_10_26.178.log`:
```
"npm" "link" "@empirica/core"
Volta v1.1.1

Could not locate the package '@empirica/core'

Please ensure it is available by running `npm link` in its source directory.

Error cause: Could not read package configuration file
from /root/.local/share/empirica/volta/tools/user/packages/@empirica/core.json

Please ensure you have correct permissions to the Volta directory.

Error cause: No such file or directory (os error 2)
```

It turns out that there is no content in `/root/.local/share/empirica/volta/tools/user/packages`, on the server (i.e. the directory `@empirica` does not exist). How do I fix this? I tried uninstalling and reinstalling Empirica, and also changing the permissions for the Volta directory. 

Note that `empirica export` works after I create a stock experiment `empirica create my-experiment` on the server, but not after I send my experiment bundle to the server and deploy the experiment using `empirica serve`. 

### Empirica Version

```text
Version: v1.3.3
SHA:     f53e816
Branch:  main
Time:    2023-05-20T03:27:58Z
```

### What OS are you seeing the problem on?

macOS, Linux

### What browser are you seeing the problem on?

Does not apply

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
This should be fixed in the latest release. please run `empirica upgrade`.

**Comment by npaton** [comment]
I've found another unrelated issue where older versions of the installer could cause problems. Please run the installer again then upgrade:

```sh
curl https://get.empirica.dev | sh
empirica upgrade --global
```
