### ISSUE TITLE
player.get("treatment") null before refresh in intro

### ISSUE THREAD

**Issue by npaton** [empiricaly/empirica#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

> we used player.get("treatment") in introSteps to get the playerCount. At first it only returns NULL, but if we refresh the page once then it can return values correctly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
Released.

**Comment by npaton** [comment]
I have many tests and I cannot reproduce this.

**Comment by yankai-wang** [comment]
As a record, the real reason is passing unmanagedGame to <EmpiricaContext>.
