### ISSUE TITLE
Admin console start button miscolored

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Super low priority, but I noticed that when we create a batch, the "start" button gets the wrong color:
<img width="1164" alt="image" src="https://github.com/empiricaly/empirica/assets/4304478/568ab9c7-9492-46a5-b838-1596d87676c4">

### Empirica Version

```text
Version: v1.4.3
SHA:     61a708e
Branch:  main
Time:    2023-07-15T02:53:33Z

Client:  1.4.3
Server:  1.4.3
```

### What OS are you seeing the problem on?

macOS

### What browser are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
This should be fixed in 1.4.6,
