### ISSUE TITLE
duplicate playerIds will lead the game to start with fewer players

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#35]
For example, if we set up a game with `playerCount=3`, we can make it start with 2 following this procedure:
- http://group-discussion.meteorapp.com/?workerId=Test1 
    - go to the lobby
- a new browser: http://group-discussion.meteorapp.com/?workerId=Test2 
    - and go to the lobby
- Then from a new browser: http://group-discussion.meteorapp.com/?workerId=Test1 
- The game will start with 2 players (instead of 3)! Although, two of the screens will be the same.

This is a highly likely scenario when working with MTurk workers (i.e., opening the URL from multiple browsers).

**Comment by npaton** [comment]
This should be fixed now.

**Comment by amaatouq** [comment]
tested
