### ISSUE TITLE
late update for the player.exitStatus

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#37]
For example, 

1. code like this will not work: 
```jsx
 ExitSteps(game, player) {
    console.log(player)
    if (player.exitStatus !== "finished") {
      return [Sorry];
    }
    return [ExitSurvey, Thanks];
  }
```
Would always display `Sorry` as by the time the player gets into the `ExitSteps` the `player.exitStatus` is still not updated to `finished`.  The update happens afterwards.

2. However, this works fine:

```jsx
  ExitSteps(game, player) {
    if (player.exitStatus) {
      return [Sorry];
    }
    return [ExitSurvey, Thanks];
  }
```

I would say that the first one is more intuitive/expected than the second one.

**Comment by amaatouq** [comment]
hmm it seems that approach number 2 doesn't always work (if things happen too quickly).

**Comment by npaton** [comment]
Should be sequential now.
