### ISSUE TITLE
Adding `object.append("key",value)` functionality

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#38]
Adding `object.append("key",value)` functionality. This will be useful for example to:

- `player.append("answer",answer)` for time series analysis of players actions (e.g., getting intermediate ansers). 
- `round.append("chat", text)` to impelement a chat between multiple users (it can happen at the stage level too) or for logging events (at any level).

**Comment by amaatouq** [comment]
needs testing

**Comment by npaton** [comment]
Seems to be working so far, closing.
