### ISSUE TITLE
Print `empirica version` at the top of logs in production

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It would be helpful to know the exact versions of empirica and the empirica/core libraries used in a production deploy, to help with debugging if there is an issue in production.

### Describe the solution you'd like

When empirica starts in production mode, print the output of `empirica version` to the console. For example:

```
2023-08-01T11:48:39.350-04:00 | Setting empirica admin pw...
-- | --
   | 2023-08-01T11:48:39.351-04:00 | Starting empirica ...
   | 2023-08-01T11:48:39.375-04:00 | {"level":"info","target":"/tmp/c48f285624c43bb2","time":"2023-08-01T15:48:39.375132708Z","message":"unbundle: installing"}
   | 2023-08-01T11:48:39.950-04:00 | {"level":"info","time":"2023-08-01T15:48:39.950659686Z","message":"serve: server started"}
   | 2023-08-01T11:48:40.117-04:00 | {"level":"info","time":"2023-08-01T15:48:40.117593584Z","message":"empirica: server started"}
   | 2023-08-01T11:48:40.117-04:00 | Version info could go here 
 ```

### Describe alternatives you've considered

In the startup script on the server, I could use the `empirica version` command, but I'm not sure if it would give me the version that is used by the bundled empirica experiment, or the version of the proxy that is going to open it

Another solution would be to be able to pass the bundle as an argument to `empirica version` and have it check the version of empirica used in that bundle.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
Fixed in 1.6.1.
