### ISSUE TITLE
onSet and onAppend callbacks

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#39]
In addition to the between games/rounds/stages callbacks, we might want to add additional callbacks that are invoked when an event within a stage happens. 

This could include a general `onSet(.)` and `onAppend(.)` callbacks or more detailed ones such as `onPlayerSet(.)`, `onRoundSet(.)`, `onStageSet(.)` and instead of `Set/Append` maybe replacing it with `onObjectChange`in order to be invoked whenever `object.set("key",value)` or `object.append("key",value)` are invoked.

**Comment by npaton** [comment]
Added with 6791675.
