### ISSUE TITLE
Players Freezing during unManaged Game when new player begins intro steps 

### ISSUE THREAD

**Issue by Jeffotter** [empiricaly/empirica#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I begin a default app and attempt to make a game with a custom assignment. I created four games,
  -  2 default 3-player games
  -  2 default 5-player games
For these games, I am doing the custom game assignment. I will attach my codes below. 
When I am adding people to the first game. (A five-person usually, although it shouldn't matter) I have the game start after two players have finished their intro checks. While these players are guessing jelly beans. I have a third player start the process  In order for they 

Input their ID -- no issues. 
Begin intro steps -- (players currently guessing jellybeans freeze to a loading screen)

When I refresh the two original players, they can now see the avatar of the new player while the new player is still in the intro steps.

Game resumes

### Steps To Reproduce

1. Create a default game
2. Make a treatment
<img width="655" alt="image" src="https://github.com/empiricaly/empirica/assets/60712345/682f4108-e7bb-42fe-9a82-5ac48ad4a81a">

3. Modify App.jsx , Stage.jsx, Callbacks.jsx, server/index.js  (code locations attached below, error was occurring before stage modification ) Custom assignment copied from here (https://github.com/JamesPHoughton/external-grouping)
4.  Start the game and create 3 Players 
5. Run 2 players through the intro steps and the game will begin
6. While the game is running, start the third player
7. After the 3rd player submits his ID the other two players will be frozen. 
8. Refresh on the two original players and see the third player who should still be in the intro steps

### Empirica Version

```text
Version: v1.6.0
SHA:     0d26251
Branch:  main
Time:    2023-08-10T11:36:38Z

Client:  1.6.0
Server:  1.6.0
```

### What OS are you seeing the problem on?

macOS

### What browser are you seeing the problem on?

Chrome

### Relevant log output

```shell
There are no errors That I can see either the console logs or the IDE logs
```

### Anything else?

https://github.com/Jeffotter/demo_unmanagedGame/blob/main/server/src/callbacks.js
https://github.com/Jeffotter/demo_unmanagedGame/blob/main/server/src/index.js

https://github.com/Jeffotter/demo_unmanagedGame/blob/main/client/src/Stage.jsx
https://github.com/Jeffotter/demo_unmanagedGame/blob/main/client/src/App.jsx

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
Thank you, @Jeffotter. I can't seem to access your repo. Would you mind adding me as a contributor with Read permission? Thanks!

**Comment by Jeffotter** [comment]
@npaton done! Sorry about that

**Comment by npaton** [comment]
It is happening because `assignPlayer` is called without `await`. To fix it, you need to add an `async` around that callback and add `await` on the `assignPlayer` line.

It took me a while to find the issue, it did not jump at me, and this is likely to cause problems for others. We'll make sure to have a warning about it in the docs when they are done. I've also created a fix for this, so that we commit all the changes even if await was not used: https://github.com/empiricaly/empirica/pull/410. But I am currently unsure about the consequences of changing this behavior, so I haven't merged it yet. TBD

**Comment by Jeffotter** [comment]
Did this work in your testing?

**Comment by Jeffotter** [comment]
async function yourFunction() {
    try {
      await slots[0].assignPlayer(player);
      slots[0].set('player_count', slots[0].get('player_count') + 1);
      // The code after this line will only execute after assignPlayer has completed.
      console.log('Player assigned successfully');
    } catch (error) {
      // Handle any errors that might occur during the assignment.
      console.error('Error assigning player:', error);
    }
  }
  
  // Call your async function
  yourFunction();
