### ISSUE TITLE
panic: runtime error: slice bounds out of range [1:0]

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Looking at my server logs, I saw this error:
Not sure what the write buffer stuff is about but this panic triggered a full server reset (it shut down the container and restarted it)

![image](https://github.com/empiricaly/empirica/assets/4304478/af88b3bb-2670-49c2-b6d2-ab03a9df7b71)

### Steps To Reproduce

Running Empirica 1.8.0 in a container (this one: https://github.com/Watts-Lab/deliberation-empirica/pkgs/container/deliberation-empirica/131811717?tag=2023-09-27_01-19-45) on AWS

### Empirica Version

```text
Version: v1.8.0
SHA:     297d560
Branch:  main
Time:    2023-09-16T08:00:40Z

Client:  1.8.0
Server:  1.8.0
```

### What OS are you seeing the problem on?

Linux

### What browser are you seeing the problem on?

Does not apply

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JamesPHoughton** [comment]
After the server restart, saw the same issues with no new server activity (but loading the same tajriba.json). This happened several times, until eventually, we had this:
![image](https://github.com/empiricaly/empirica/assets/4304478/2caa5c5f-e4a8-402e-a710-07693bfe88a4)
![image](https://github.com/empiricaly/empirica/assets/4304478/7252315d-3c9d-4563-9d94-320bdb65aade)

**Comment by npaton** [comment]
It seems to be related to this issue: https://github.com/empiricaly/empirica/issues/379#issuecomment-1666867483
Zombie connections. I will try to take a look as soon as possible, but I don't think reverting to an older version will help. I need to find out why it's not dropping the connection and why it puts the database in a bad state.

**Comment by npaton** [comment]
I took a look, and I apologize, there's no way I can fix this by tomorrow. But I will take a closer look over the weekend.

**Comment by JamesPHoughton** [comment]
Had this again today - luckily we were able to get a lot of good data, and the error only happened after about 45 minutes of activity, so we'd had several groups complete the whole study. I'd been getting periodic `"changes: conn write timeout"` and `"changes: write buffer full, abandoning connection"` throughout, and then at the end we had a slew of ~30 and then this error message:

![image](https://github.com/empiricaly/empirica/assets/4304478/483b8286-368b-47f4-825d-5d1c9f519b71)

Let me know if I can dig up any more info or test anything. =)

**Comment by npaton** [comment]
This should be fixed in the latest release. please try upgrading. 🙏
