### ISSUE TITLE
Setting callback to game object results in undefined

### ISSUE THREAD

**Issue by frasalvi** [empiricaly/empirica#417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am trying to `set` a custom callback as an attribute of `game` objects, when they are created. However, as soon as the game starts, when I try to `get` my callback, that turns out to be undefined.

### Steps To Reproduce

1. In the default application, append at the end of server/src/callbacks.js the following snippet

```
function testCallback() {
  console.log("Here is testCallback");
}

Empirica.on("game", (ctx, { game }) => {
  if (game.get("customInitialised")) return;
  game.set("customInitialised", true);

  game.set("myCallback", testCallback);
  console.log("My callback is ", game.get("myCallback"));
});

Empirica.on("game", "status", (ctx, { game, status }) => {
  console.log("Game status changed to", status);
  console.log("My callback is ", game.get("myCallback"));
  game.get("myCallback")();
});
```
2. Create and start a batch with one "Solo" game
3. Create a player and complete intro steps

### Empirica Version

```text
Version: v1.8.0
SHA:     297d560
Branch:  main
Time:    2023-09-16T08:00:40Z

Client:  1.8.0
Server:  1.8.0
```

### What OS are you seeing the problem on?

Windows

### What browser are you seeing the problem on?

Chrome

### Relevant log output

```shell
[server] My callback is  [Function: Hie]
[server] Game status changed to running
[server] My callback is  undefined
[server] 21:24:23.464 ERR Error caught in "game.status" callback:
[server] 21:24:23.532 ERR TypeError: t.get(...) is not a function
[server] 21:24:23.533 ERR /mnt/c/Users/salvi/Desktop/EPFL/Thesis/testExp/server/src/callbacks.js:75
[server] 21:24:23.533 ERR game.get("myCallback")();
[server] 21:24:23.533 ERR ^
[server] 21:24:23.533 ERR   at Object.callback (/mnt/c/Users/salvi/Desktop/EPFL/Thesis/testExp/server/src/callbacks.js:75:24)
[server] 21:24:23.533 ERR   at Object.next (/mnt/c/Users/salvi/Desktop/EPFL/Thesis/testExp/server/node_modules/@empirica/core/src/admin/cake.ts:322:30)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
You can only set values that are JSON serializable. JavaScript functions are not JSON serializable. I will add a note to our docs.

**Comment by npaton** [comment]
https://github.com/empiricaly/docsv2/issues/6
