### ISSUE TITLE
Game loading takes too long

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#44]
At the moment, after the game became much smoother (i.e., using the new data loading scheme), the waiting time before the game starts (game loading) takes too long, relatively. Also, when the game loading page disappears we still have `<\loading>` for a second before the first stage runs.

**Comment by amaatouq** [comment]
Maybe we want to think again about the 'preparing the game' page and how it is implemented given the new data loading scheme.

**Comment by npaton** [comment]
I think we can eventually eliminate this almost entirely. So we have a baseline, it would be nice to to have 2-3 measurements (in seconds) from various existing various deployed experiments.

**Comment by amaatouq** [comment]
Actually, this seems to be most sensitive to the number of rounds (number of players/stages have little/no effect). the RME takes way longer (1 player; 1 stage; 36 rounds), than the interactive-estimation of dot directions (3 players; 9 stages, 20 rounds).

**Comment by npaton** [comment]
First step for this ticket, I'll instrument the init function of a few experiments and we can see exactly what's happening. Maybe after the new API for init (addRound, get, set, etc) so I can automatically instrument all init functions at once. ;)

**Comment by amaatouq** [comment]
this was fixed when we changed the subscribe/publish method
