### ISSUE TITLE
`RangeError: Max payload size exceeded` when running `empirica export`

### ISSUE THREAD

**Issue by aliciamchen** [empiricaly/empirica#442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Sometimes when I run `empirica export` it gives me an error and is not able to create the CSVs (it makes the `.zip` file, but the file is empty) 

Is it possibly related to the size of the `tajriba.json` file? I have a script that copies the `tajriba.json` file from the server to my computer every five minutes while I'm running an experiment, and I noticed this usually happens in the middle of an experiment run, where earlier `tajriba.json` files can `empirica export` but not later `tajriba.json` files. 

I've attached two `tajriba.json` files. For this one, `empirica export` works:
[tajriba_export-works.json](https://github.com/empiricaly/empirica/files/13468589/tajriba_export-works.json)

And for this one, `empirica export` does **not** work: 
[tajriba.json](https://github.com/empiricaly/empirica/files/13468586/tajriba.json)

### Steps To Reproduce

This happens both when I run `empirica export` on my server and also on my local machine (see below for details)

### Empirica Version

```text
Version: v1.8.5
SHA:     1d91ea7
Branch:  main
Time:    2023-11-16T03:03:22Z

Client:  1.8.5
Server:  1.8.5
```

### What OS are you seeing the problem on?

macOS

### What browser are you seeing the problem on?

Does not apply

### Relevant log output

GitHub doesn't accept comments longer than 65553 characters, so I've put the console output in a Google Doc here: https://docs.google.com/document/d/1P-RTDfzyRQ2LjoqEm8M2Eb0s5O_paMJF5zTUuj2G20U/edit?usp=sharing

### Anything else?

Typically what I do to run `empirica export` is copy `tajriba.json` from the server to `.empirica/local` on my computer, and then run `empirica export` on my computer. 

`empirica export` does not work on the server (when I run the experiment using `empirica serve` after `scp`-ing the bundle file) unless I `empirica create` a boilerplate experiment on the server, and then move `tajriba.json` to that experiment directory and run `empirica export` from that directory. I tried doing this for the `tajriba.json` files that could not export, and it gave me the same errors. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
This should be fixed in the latest release. You'll want to upgrade your project. And you might need to change your `.empirica/release` file in the dir where you ran the `serve`. Let me know how it goes.

**Comment by aliciamchen** [comment]
Thank you so much, it works with `1.8.9`!
