### ISSUE TITLE
module cross-fetch error in 1.8.8 and fail to change version to 1.8.7

### ISSUE THREAD

**Issue by yankai-wang** [empiricaly/empirica#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrading to 1.8.8, I got the following error which doesn't show up in 1.8.6:
`Uncaught SyntaxError: The requested module '/node_modules/cross-fetch/dist/browser-ponyfill.js?v=5331b651' does not provide an export named 'default'`
and I can't change my version to 1.8.7:
`Error downloading: https://install.empirica.dev/empirica/darwin/arm64/version/v1.8.7/empirica
16:09:01.919 FTL empirica: failed to start error="upgrade command: upgrade globally: download binary: http fetch: server returned 404 Not Found"`

### Empirica Version

```text
1.8.8
```

### What OS are you seeing the problem on?

macOS

### What browser are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
This should be fixed in release 1.8.9.
