### ISSUE TITLE
The value of usePlayers is sometimes undefined

### ISSUE THREAD

**Issue by npaton** [empiricaly/empirica#455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The `usePlayers` sometimes returns undefined, while it shouldn't. `usePlayer` and `useGame`, at the same time, are returning something. In no circumstance should `usePlayers` be undefined while the others are defined. It seems that it's a loading issue. If you check for undefined, and wait shortly, it will become available relatively quickly.

### Steps To Reproduce

1. Reload the experiment in the middle of a stage and use `usePlayers`, and it's sometimes undefined

### Empirica Version

```text
1.8.9
```

### Anything else?

It's likely waiting to have all the players loaded to return anything. Question is:
1. do we return before all players have loaded (partial list inside usePlayers)
2. do we wait to have all players loaded before we allow the app to render (probably preferable)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by frasalvi** [comment]
Encountered this (thanks to Sentry) with one participant that had a bad connection and kept disconnecting and reconnecting.
