### ISSUE TITLE
Warnings in `1.8.11`

### ISSUE THREAD

**Issue by aliciamchen** [empiricaly/empirica#468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I get this warning every minute or so, don't think I've seen this with previous versions: 
`20:08:48.576 WRN failed load: [GraphQL] transition step: invalid transition: from state mismatch with previous state`

### Empirica Version

```text
Version: v1.8.11
SHA:     fce31f9
Build:   154
Branch:  main
Time:    2023-12-20T10:26:18Z
```

### What OS are you seeing the problem on?

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
I removed these unnecessary warnings in the latest version.

**Comment by aliciamchen** [comment]
Thanks. I have also been getting this warning in `1.8.12`, though less frequently.

**Comment by HuangHam** [comment]
I also have been seeing this warning lately even in v1.11.3. It comes up some of the time and doesn't seem to do freeze the experiment so I still manage to obtain data. But some participants complained that they have to refresh the page to proceed. I don't know if this is directly related to the warning or not. What does this warning mean? Is it concerning?

**Comment by npaton** [comment]
It should not happen in 1.11. Did you upgrade your server version of `empirica` recently? (curl…)

**Comment by HuangHam** [comment]
Yes I checked through empirica version and sure enough it is v 1.11.4

**Comment by HuangHam** [comment]
What causes it is this line of code where I try to end the stage if the time reaches 10s:

`useEffect(() => {
    // Set the timer for 10 seconds
    const timer = setTimeout(() => {
      // Run your function after 10 seconds
      if(!is_practice){
        console.log('timeup!')
        player.round.set("is_manually_ended", true);
        player.stage.set("submit", true);} // I think having this causes warning WRN failed load: [GraphQL] transition step: invalid transition: from state mismatch with previous state
    }, 10000); // 10000 milliseconds = 10 seconds`
