### ISSUE TITLE
Error caught in `round.start` callback; cannot read properties of undefined (reading 'round')

### ISSUE THREAD

**Issue by aliciamchen** [empiricaly/empirica#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I got another `round.start` callback error that is different from before (#467). After I got the error in the console, participants saw an infinite spinny circle and were not able to continue the game. I did receive a tiny bit of data on my console after I got this error (indicating some participants were still able to do the task), but after a few seconds the data stopped coming in and none of the participants were able to proceed. 

This error does not happen every time I run the experiment. 

The admin console also reset but if I waited long enough it would show the players and games (but sometimes it would reset again) 

### Empirica Version

```text
Version: v1.8.12
SHA:     656d19b
Build:   159
Branch:  main
Time:    2023-12-26T07:14:40Z
```

### What OS are you seeing the problem on?

macOS

### Relevant log output

```shell
17:30:16.323 ERR Error caught in "round.start" callback:
17:30:16.506 ERR TypeError: Cannot read properties of undefined (reading 'round')
17:30:16.506 ERR   at <anonymous> (/tmp/2fe66e9b1d711942/src/callbacks.js:65:11)
17:30:16.506 ERR   at <anonymous> (/tmp/2fe66e9b1d711942/node_modules/@empirica/core/src/admin/classic/proxy.ts:54:9)
17:30:16.506 ERR   at Object.callback (/tmp/2fe66e9b1d711942/node_modules/@empirica/core/src/admin/events.ts:91:11)
17:30:16.506 ERR   at Object.next (/tmp/2fe66e9b1d711942/node_modules/@empirica/core/src/admin/cake.ts:322:30)
17:30:16.506 ERR   at runMicrotasks (<anonymous>)
17:30:16.506 ERR   at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
FYI, I am still working on this one and #467, which seem to be related.

**Comment by aliciamchen** [comment]
Thank you! I have also been getting this error, in `1.9.2`: 

```
00:36:20.490 ERR Error caught in "stage.ended" callback:
00:36:20.548 ERR TypeError: Cannot read properties of undefined (reading 'stage')
00:36:20.548 ERR   at <anonymous> (/tmp/220f55abc589d820/src/callbacks.js:110:13)
00:36:20.548 ERR   at <anonymous> (/tmp/220f55abc589d820/node_modules/@empirica/core/src/admin/classic/proxy.ts:82:9)
00:36:20.548 ERR   at Object.callback (/tmp/220f55abc589d820/node_modules/@empirica/core/src/admin/events.ts:91:11)
00:36:20.548 ERR   at Object.next (/tmp/220f55abc589d820/node_modules/@empirica/core/src/admin/cake.ts:322:30)
00:36:20.548 ERR   at runMicrotasks (<anonymous>)
00:36:20.548 ERR   at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by npaton** [comment]
Ok, thank you. Yeah, this is a big one I have left remaining. I'll get to it asap.

**Comment by npaton** [comment]
I don't think this is happening anymore. Please reopen if you're still seeing this.
