### ISSUE TITLE
"log" option in `.set()` and `.append()`

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#51]
it seems to me that there are two distinct usages for the `.set()` and `.append()`:
1. for reactivity and sharing/synchronizing data across clients
2. for logging actions in the database for later analysis (i.e., `.get()` will never be invoked for those keys). 

So it seems to me that if an experiment is logging a lot of data (i.e., as in time series for all the actions happening in the game), then it might be wasteful to have the data published on the client-side when it is not going to be used. This might, later on, have performance implications. 

I am suggestions to add a `log` options e.g., `object.append("key", value,"log")` that will indicate to empirica that this value will never be called in the game, and does not have to be published to the client.

What do you think?

**Comment by npaton** [comment]
Yep, that would make sense.
