### ISSUE TITLE
player.set not working in onStageStart

### ISSUE THREAD

**Issue by yankai-wang** [empiricaly/empirica#515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In `Empirica.onStageStart`, I reset the submission status of each player with the following codes:
```
 players.forEach((player) => {
    player.set("satisfied", false);
  });
```
But since 1.8.12, it's not working.

### Steps To Reproduce

- In the admin page, create a new game with treatments "full_decom_add_growFromIndiv". 
- Finish the first round, then add another player to start the second round. 
- In the second round, the old player's submission status would be true, though it should be false (indicated by the check/cross mark on the avatar).
<img width="178" alt="image" src="https://github.com/empiricaly/empirica/assets/85508543/fdaad371-f6b1-4184-b27d-0170a9170050">

- In server's console, outputs are:
```
[server] before reset satisfied true
[server] reset satisfied true
[server] before reset satisfied true
[server] reset satisfied false
```
but satisfied should always be false after resetting. 

### Empirica Version

```text
1.8.12
No problem observed in 1.8.11 and versions before.
```

### What OS are you seeing the problem on?

macOS

### What browser are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
Released in 1.9.7
