### ISSUE TITLE
Unable to run earlier versions of Empirica v1

### ISSUE THREAD

**Issue by Shawnhan666** [empiricaly/empirica#516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I attempted to run an early version of an Empirica game, specifically Version 1, from the GitHub repository (https://github.com/srflet/crowd-emotions-v2-pilot). After cloning the repository locally and successfully running `**meteor npm install**`, I encountered a version compatibility issue when trying to launch the game using Meteor. The terminal displayed the following message: 

"This project uses Meteor 1.10.2, which isn't available on this platform. To work with this app on all supported platforms, use meteor update --release METEOR@2.15 to pin this app to the newest compatible release." 

Following the suggested advice, I executed `**meteor update --release METEOR@2.15**`. However, this led to initialization errors related to package version conflicts:

=> Errors while initializing project:                                       
While selecting package versions:
error: Conflict: Constraint accounts-password@1.6.0 is not satisfied by accounts-password 2.4.0.
Constraints on package "accounts-password":
* accounts-password@~2.4.0 <- top level
* accounts-password@1.6.0 <- empirica:core 1.16.1

Conflict: Constraint accounts-base@1.4.2 is not satisfied by accounts-base 2.2.10.
Constraints on package "accounts-base":
* accounts-base@~2.2.10 <- top level
* accounts-base@1.4.2 <- matb33:collection-hooks 0.9.1 <- empirica:core 1.16.1
* accounts-base@2.2.9 <- accounts-password 2.4.0 <- empirica:core 1.16.1

These constraints indicate a significant compatibility issue between the early version of the Empirica game I'm trying to run and the newer Meteor platform versions.   How can I resolve these version conflicts to successfully run the game?

Thank you!!

### Steps To Reproduce

1. clone from https://github.com/srflet/crowd-emotions-v2-pilot
2. how to run it successfully locally?

Thanks!!!!!

### Empirica Version

```text
METEOR@1.10.2
```

### What OS are you seeing the problem on?

macOS

### What browser are you seeing the problem on?

Does not apply

### Relevant log output

```shell
shawn@eduroam-int-dhcp-97-32-197 crowd-emotions-v2-pilot % meteor                             
This project uses Meteor 1.10.2, which isn't available on this platform. To work with this app on all supported platforms, use meteor update --release METEOR@2.15 to pin this app to the
newest compatible release.
shawn@eduroam-int-dhcp-97-32-197 crowd-emotions-v2-pilot %  meteor update --release METEOR@2.15
=> Errors while initializing project:         
                                              
While selecting package versions:
error: Conflict: Constraint accounts-password@1.6.0 is not satisfied by accounts-password 2.4.0.
Constraints on package "accounts-password":
* accounts-password@~2.4.0 <- top level
* accounts-password@1.6.0 <- empirica:core 1.16.1

Conflict: Constraint accounts-base@1.4.2 is not satisfied by accounts-base 2.2.10.
Constraints on package "accounts-base":
* accounts-base@~2.2.10 <- top level
* accounts-base@1.4.2 <- matb33:collection-hooks 0.9.1 <- empirica:core 1.16.1
* accounts-base@2.2.9 <- accounts-password 2.4.0 <- empirica:core 1.16.1

shawn@eduroam-int-dhcp-97-32-197 crowd-emotions-v2-pilot % meteor list

This project uses Meteor 1.10.2, which isn't available on this platform. To work with this app on all supported platforms, use meteor update --release METEOR@2.15 to pin this app to the
newest compatible release.
shawn@eduroam-int-dhcp-97-32-197 crowd-emotions-v2-pilot %
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by malsobay** [comment]
This is a known issue with Apple silicon -- see [this part](https://docsv1.empirica.ly/getting-started/setup#a-note-about-macos-monterey-apple-m1-chip-setup) of the v1 documentation. 

In case you want to run it on your Mac, this is what I do:
1. If you run arch in your terminal, you can see which architecture your terminal is using. If you're on M2, this'll show `arm64`, but if you emulate Intel, you should see `i386`
2. To run a v1 project, you first need to emulate the Intel architecture, which is what the docs I shared above suggest. To make this easier, I've added an alias to my `.zshrc` file. What this does is allow me to type `intel` into the terminal to emulate `i386` only for the current terminal session (i.e. any other terminal window will still be `arm64`, so you won't mess anything up.)
```alias intel="arch -x86_64 zsh"```
Then, whenever you want to launch a v1 project, from within the project directory you just need to do:
```
>> intel 
>> meteor
```
