### ISSUE TITLE
getting additional data from the url

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#52]
like `workerId` one might want to get the `hitId` from the url too. Is there a way to get all the data from the URL (if the option is enabled from the settings?).

`workerId` can be generalized to `playerId` in the url, and this can be stored in the `player.id` object and skips the identification page. 

Then maybe we have something called `urlParameters` on the player object which will include all additional parameters provided in the URL as key/value pairs.

**Comment by joshua-a-becker** [comment]
In order to store all URL params as a player datum, I added the following code to Public.jsx:

```
//roll our own because iterators don't seem to work...
vanillaGetParams() {
	const queryString = window.location.search.substring(1);
	const params = {};
	var temp;
	// Split into key/value pairs
	const queries = queryString.split("&");
	// Convert the array of strings into an object
	for (var i = 0; i < queries.length; i++ ) {
			temp = queries[i].split('=');
			params[temp[0]] = temp[1];
	}
	return params;
}


storeParams = () => {
	const player=this.props.player;
	
	// get URL params using a custom function that doesn't require iterators
	const urlParams = this.vanillaGetParams();
	
	// store all URL params as a player datum		
	Object.keys(urlParams).forEach(function(key){
		console.log(key + ": " + urlParams[key]);
		player.append(key, urlParams[key]);
	});
	
	// note that they have been set so we don't do it again
	player.append("urlParamsStored",new Date().getTime());
}

componentWillUpdate() {
	const player = this.props.player;
	// when the player object is ready, store the URL params
	if(player) {
		if(player.append) {		
			// only store them once
			if( !Object.keys(this.props.player.data).includes("urlParamsStored")) {
				this.storeParams();		
			}
		}
	}
}
```

**Comment by joshua-a-becker** [comment]
The only issue with this is that it seems to store data as an array.   ¯\_(ツ)_/¯

**Comment by amaatouq** [comment]
I am late to the party and not sure if I get the issue. But is it related to #52 https://github.com/empiricaly/empirica/issues/52 ?

**Comment by joshua-a-becker** [comment]
hmmm this failed on at least one try; i'm not sure why.  possibly if the user gets immediately assigned to a game...?  so the component doesn't "update" it just renders and moves on?

**Comment by joshua-a-becker** [comment]
in retrospect it's also possible i simply failed to enter the datum that one time.

**Comment by npaton** [comment]
I’ve went ahead and added this to core. Now all URL params are saved in the player object under a new key called `urlParams`. I wanted to keep it separate from normal user `data`, to avoid unintended conflicts. Now you can access url params from anywhere with the user. e.g. `player.userParams.myURLParameter`. I think that should solve the issue, let me know know @joshua-a-becker (note, this is part of the new packaged empirica, I did not add it back to empirica “classic”. New empirica will be released shortly).

**Comment by joshua-a-becker** [comment]
i also did end up putting it in both `componentDidMount()` and `componentDidUpdate()` and it seems to work reliably
