### ISSUE TITLE
everything appears duplicated in the admin

### ISSUE THREAD

**Issue by npaton** [empiricaly/empirica#559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In production (at least), everything seem to appear duplicated in the admin UI (batches, games, players…)

### Empirica Version

```text
Latest
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
This happened when 2 instances of the empirica nodejs backend were running at the same time. We need to find a way to avoid this situation. Not sure how it happened in this case, but it should of course never happen if you don't want it to.

**Comment by dharakyu** [comment]
I think I am seeing this problem too (v1.11.2). When creating a batch with 1 game through the admin console, sometimes I observe that there is a duplicate game created, such that there are 2 games in the batch. The assignment logic then seems to break (players are shown as paired off with each other within the batch, on the console, but the spinning circle appears for both players' views).

**Comment by npaton** [comment]
If this happens, I'd recommend checking whether there are 2 instances of the callbacks running at the same time. In production (empirica server), you can check by running `ps aux | grep node` and see if there are 2 `node` commands running.
