### ISSUE TITLE
8s stage occasionally takes longer (way longer)

### ISSUE THREAD

**Issue by HuangHam** [empiricaly/empirica#570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have a stage that should take 8s: round.addStage({name: "maintenance", duration:8}); but I receive feedback from some prolific participants that at some trials, it "freeze" at this stage but later it was able to proceed. When I looked at the duration data I recorded I indeed found that each subjects had some trials where this stage took extremely long: like over 1 min or 2 min sometimes. I don't know how to reproduce this problem because on my local server it works fine. I wonder maybe my digitalocean is not powerful enough so occasionally heavier traffic causes the server to "pause" a subject's task?

### Empirica Version

```text
v1.11.3
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HuangHam** [comment]
Follow-up: the "freezing" might be a separate issue from the timing. I made too many player.set or player.round.set in a stage and too many renders of url images which causes the freezing. But once I fixed all that the timing issue still persists (though not as extreme as before). It happens even in stages where I literally just present a string of text for 1 second.

**Comment by npaton** [comment]
I think this is fixed.
