### ISSUE TITLE
Trouble starting bundle on server -- ERR context: global scopeID not fetched: [GraphQL] Cannot query field "ephemeral" on type "Attribute"

### ISSUE THREAD

**Issue by collinskatie** [empiricaly/empirica#573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi, I am trying to start our project bundle from an AWS EC2 instance; however, receive the following error when running` empirica start`

`ERR context: global scopeID not fetched: [GraphQL] Cannot query field "ephemeral" on type "Attribute" `

We have tried re-curling empirica on the server.

### Steps To Reproduce

Running 

`empirica serve [bundle]`

on AWS EC2 instance

After having run: 

`curl -fsS https://install.empirica.dev/ | sh`

### Empirica Version

```text
v1.11.4 on both the server and local machine where we bundled the project
```

### What OS are you seeing the problem on?

Linux

### What browser are you seeing the problem on?

Does not apply

### Relevant log output

```shell
ERR context: global scopeID not fetched: [GraphQL] Cannot query field "ephemeral" on type "Attribute"
```

### Anything else?

Thanks for any help! 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
This should not be possible, as this error indicates the server does not know the field called ephemeral. If the server is up to date, it has the field ephemeral. 

Are you maybe using Docker to deploy your experiment? If so, you need to upgrade it too.
