### ISSUE TITLE
When stage unmounts player.round becomes undefined.

### ISSUE THREAD

**Issue by HuangHam** [empiricaly/empirica#574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to record some data when a stage ends by using 
```
useEffect(() => {
    return () => {
      console.log('Component unmounting:', player, player.round);
      recordData();
    };
  }, []); 
```
However, when the stage unmounts, player is defined but player.round is not defined, which is odd. So I cannot record data into player.round in the function recordData. 

### Empirica Version

```text
v 1.11.4
```

### What OS are you seeing the problem on?

macOS

### What browser are you seeing the problem on?

Chrome

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'set')
    at recordData (Maintenance.jsx:151:20)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
It is unfortunately not possible to record data as the component unloads at the end of a round, since the round has ended at that point.
