### ISSUE TITLE
expose more UI elements to experimenter

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/empirica#58]
Currently, certain elements needed to control the visual experience are contained in core code.  While developing my own experiment, I had to alter Breadcrumbs.jsx and Game.less and I can imagine there would be times when I need to alter Game.jsx .  I had to alter breadcrumbs.jsx in order to restart round counting at 1 after a certain point (after "training" rounds were complete) and i had to alter Game.less just because i have certain stylistic preferences.

It's not totally clear to me that all of these "should" be exposed to the experimenter, because there are always going to be elements that some power users want to modify, and it can be valuable to keep things simpler for the less experienced coder/experimenter.   So Abdullah encouraged me to open an isuse. :)

**Comment by npaton** [comment]
This makes sense. We can have replaceable defaults. At the moment, in the experiment, on the client side, you are required to give a React component called `Round`, which should contain the experiment. We can extend this by allowing people to set a `Game` component, which would replace the entire UI around the `Round` (Round still required). The `Game` component does contain the breadcrumb (which is not an ideal name, the breadcrumb is traditionally a UI component that tracks a page hierarchy, not a progress, we can rename that eventually). We could still allows people to just replace the breadcrumb/progress indicator only the same way, if they don't want to tackle the entire UI and just need functional changes to that component.

Side note, we did at some point have the "breadcrumb" inside the `Round`, which allowed for potentially easier replacement, but we removed it so we could keep it visible between stages/rounds, to make transitions less brutal for the players: they would always see progress even during the interstage moments. I think this is still a good default, and it can be overridden with this full `Game` replacement technique.

A couple other things we have talked about are to have a few options in the backend to do sweeping changes to the UI: colors, font, logo, etc. This would not need to be exclusive of the complete replacement option, the 2 are orthogonal features.

Lets keep this feature request open to track all of that.

**Comment by amaatouq** [comment]
Yes, I think feature #1 will eventually cover most of the needs for exposing the `Game.js` and `Game.less` to the experimenter. If something more is needed, then the experimenter can edit the `core`.

As for the breadcrumb, as @npaton mentioned, we want to keep it visible between stages/rounds (i.e., without reloading). Otherwise, the transitions become very rough.

I wonder if there is a trick where the experimenter can indicate which components to reload between stages/rounds and which ones to stick (i.e., to exist at the game level, not the round)?  I can imagine, for many experiments, we want things like `PlayerProfile` to also not to reload on every transition (i.e., because it is there across all stages/rounds)..  Is there a way for example to wrap the component that you don't want to reload with another component that controls where it lives? 
something like:

```react.js
<sticky>
    <Breadcrump .... />
</sticky>

<Task     ....  />

<sticky>
    <PlayerProfile ....>
</sticky>
```

So only the Task is the one reloading?

**Comment by joshua-a-becker** [comment]
wouldn't it be sufficient to just move the file location of Breadcrumb.jsx to "imports/experiment/client/game

**Comment by npaton** [comment]
@amaatouq There is no way to not render nodes unless they are marked for render, that I know of. We could do some sort of trickery with inspecting children. But that would only work at the first level of children, and would force people to not nest any <sticky> tags, which people totally do and wonder why it doesn't work. It would end up being more complicated than it looks like. The default behavior needs to be as easy as possible.

@joshua-a-becker I do not want the core to be importing things from the experiment too much. It's already doing it for the client and server configurations, and I'm not too happy about that.
Also, for the Game component, we need to be able to conditionally show or not the round UI and breadcrumb depending on the state of the game. I'm not too keen on adding a prop for the interstage requiring experimenters to manually hide parts of the UI (i.e. if this.props.interstage). If they fail to do so, things could break during the interstage (missing data), and the issue would be very confusing. I think it's ok to give the advanced users options to do that, without requiring them to edit the "core", but the default should be as straight forward as possible (not worrying about data availability is a big one).
