### ISSUE TITLE
Admin UI separation of monitoring from configuring

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#6]
It seems that the admin UI can be split into 3 tabs/categories:
1. ***Configurations***: things that happen before you actually run the experiment
2. ***Monitoring***: things that happen during & after running experiments .. things like creating batches, monitoring on-going games, exporting data
3. ***Advanced Settings***: The JSON file we currently have

**Comment by npaton** [comment]
I can’t actually add the settings.json editing into the UI. But if we do move away from the standard Meteor setting.json type app config, we might be able to do something about it. For now, only seperating Monitoring and Configuration.
