### ISSUE TITLE
Blank page for overbooked participants

### ISSUE THREAD

**Issue by chri4354** [empiricaly/empirica#61]
I run a large experiment on Empirica, recruiting participants on MTurk. It is usually advisable to overbook, to be sure that all slots were filled. However, I received a lot of complaints by people who accepted the HIT, read instructions and consent form just to get to a blank page because all game had reached capacity. I suggest two fixes: 1. Rather than a blank screen, tell participants what happened or 2 (RECOMMENDED) redirect participants to other groups that have not yet reached capacity. This will actually avoid rewarding people who skim through the instructions (or skipped them all together) and gain on people who actually have read them carefully.

**Comment by npaton** [comment]
We changed the algorithm for assignment, we now move players to a game with the same treatment if the game they were waiting for started and was overbooked.

If they are still in an overbooked situation and there are not more same-assignment games left, they should be redirected to the exit steps, which are configured in the `/imports/experiment/client/index.js` file (see https://github.com/empiricaly/empirica/blob/master/imports/experiment/client/index.js#L35-L37 for an example of how to return components to be shown on exit). There should not be a blank screen if this is configured properly.

I'm closing this issue for now, please test the changes we've made, and feel free to reopen this issue if you are still seeing problems.

**Comment by chri4354** [comment]
I checked my code and I have the same configuration:
ExitSteps(game, player) {
    return [ExitSurvey, Thanks];

Still my participants experienced a blank page without being offered any exit survey or explanation. Furthermore, I tested more participants yesterday and this time, even participants who completed the experiment could not go to the survey part and experienced blank page. I will open a new issue for this one, although they might be related

**Comment by npaton** [comment]
I've found the issue in your specific case, which was due to the way the ExitSurvey was implemented, it wasn't ready for players that did not play the game.
