### ISSUE TITLE
Blank page instead of being redirected to Exit survey

### ISSUE THREAD

**Issue by chri4354** [empiricaly/empirica#64]
I tested larger groups (about 15) yesterday and this time, participants who completed the experiment could not go to the survey part and experienced blank page. This is one of the participants' reports:
" [after the last question] I was met with "Waiting for server response... Please wait until all players are ready. If this takes more than 5 seconds, please Refresh the page." I refreshed the page multiple multiple times over the course of 10-15 minutes to no avail. This happened to several other people who participated as well." 

Similar responses from other turkers. Maybe it was just a connectivity problem rather than an Empirica issue, but I just wanted to bring it to your attention.

If I check my experiment admin page I see that the batch is still in "running" even though it should have ended yesterday!

**Comment by npaton** [comment]
This seems to be some sort of issue in the background job. I can't really tell what's going on with this issue without seeing the app's logs. Could you provide me with access to the app's deployment or send me logs?

**Comment by amaatouq** [comment]
I don't know, I couldn't replicate it on any of my experiments on the main empirica default app. I'll close this issue, if it persists, then @chri4354 should add the issue to the repository of the particular experiment where this is happening.
