### ISSUE TITLE
no `player._id` in exitSteps when `gameFull` 

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#65]
We might want people to still submit an exit code on MTurk, so we need to show them `player._id` .. at the moment, this does not exist at the exit survey steps (i.e., Sorry.jsx) when player `exitStatus` is `gameFull`

**Comment by npaton** [comment]
You are having problems accessing `player._id` in a Sorry.jsx? If you have access to `player.existStatus`, `player._id` should be available.

**Comment by npaton** [comment]
I just checked, `player._id` is accessible in the exit steps on `gameFull`. Reopen if you find otherwise.
