### ISSUE TITLE
variables.less declarations are not working

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/empirica#66]
After building on one dev server, then trying to clone my github to another dev server, I am getting the following error:
```
Errors prevented startup:

While building for web.browser:
imports/core/ui/components/Loading.less:36:9: variable @loading-color is undefined
imports/core/ui/components/Game.less:22:10: variable @page-height is undefined

While building for web.browser.legacy:
imports/core/ui/components/Loading.less:36:9: variable @loading-color is undefined
imports/core/ui/components/Game.less:22:10: variable @page-height is undefined

Your application has errors. Waiting for file change.
```

You can see the error in action (as of this posting) here:
	http://classrooms.smith.kellogg.northwestern.edu:3000/

But not here (as of this posting):
	http://joshua-a-becker.com/correlation 

The first one (kellogg) is a clone of the second one (joshua-becker) via this GIT respository:
	https://github.com/joshua-a-becker/learning_empirica 

I have encountered this error previously, when I first started the tutorial, but was able to “fix” it by starting over from scratch.  But in this case, I am unable to resolve the issue.  It appears that for whatever reason the build process is skipping variables.less 

Has anyone reported this before / does anyone have any recommendations?

**Comment by joshua-a-becker** [comment]
Resolved, sort of:  this error was fixed when i removed @blueprintjs/table from packages.json and re-ran `meteor npm install`

It was vestigial, since I built my own table.  But what if I really needed to use that package?

**Comment by amaatouq** [comment]
likely to be related to #12 and will be fixed by updating the package.

**Comment by npaton** [comment]
Indeed, we will be updating Blueprint to v3 with #12 as @amaatouq mentioned. In the mean time, you *should* be able to use the advanced Blueprint tables at version 1.x.x. It looks like you installed an incompatible version (3.x.x) at some point: https://github.com/joshua-a-becker/learning_empirica/commit/d0c784fb5e368b225d508e9000cc3cabff7aaa4b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R18. It does look like you are not using that package from there on, and if you didn't `meteor npm install` on that first machine, you wouldn't have noticed the broken dependency.

Why this incompatible NPM package version resulted in less variables getting lost is beyond me, and will remain so, there's just so much mystery in package dependencies, we can't control everything as well as we should unfortunately. Welcome to "modern" JS development. :)

I'm closing this ticket as I don't think there's anything else to do about this, and we will be addressing the overall issue with #12.
