### ISSUE TITLE
"No experiments available" to subjects when experiments are available in admin

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/empirica#67]
This issue occurs only when I try to use remote (hosted by mlab) database.  

Deployed with the following line:
`MONGO_URL="mongodb://user:password@myserver.mlab.com:12345/dbname" meteor --settings settings.json`

With similar results obtained when deploying on galaxy.meteor.com using 
`DEPLOY_HOSTNAME=galaxy.meteor.com meteor deploy correlation-game.meteorapp.com --settings settings.json`

I can confirm that the admin is using the mlab database in both cases because the batches/treatments/conditions carry-over across deployments (eg, on my dev server vs the galaxy server) .

You can see this in action on my digitalocean VPS:
http://159.65.180.188:3000/ [subject endpoint]
http://159.65.180.188:3000/admin [user:admin password:p@ssw0rd]

Any advice?

**Comment by amaatouq** [comment]
Did you merge with the latest empirica update?

**Comment by joshua-a-becker** [comment]
I just now updated to the latest commit (3 days ago) but it does not seem to resolve the issue

same locations as above, and here is my git in case its useful:
https://github.com/joshua-a-becker/learning_empirica

**Comment by joshua-a-becker** [comment]
To be sure, after updating I:
- deleted all collections on mlab (to ensure a fresh start)
- `meteor reset`
- rebuilt conditions/treatments/lobbies/batches
- ran meteor again using the command above

**Comment by joshua-a-becker** [comment]
UPDATE: It seems to work as long as i don't use the `--settings ` option

**Comment by joshua-a-becker** [comment]
RESOLVED:  User (dev) error!    

I had copied the settings.json from the instructions, which had playerIdParamExclusive=true BUT i was not supplying a playerId in the URL.  (H/T abdullah!)

**Comment by npaton** [comment]
Hum, playerIdParamExclusive should not break anything if playerIdParam is not present.

**Comment by npaton** [comment]
And my bad, gotcha, you did have playerIdParam as well...
