### ISSUE TITLE
missing index on db

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#68]
There are missing indices in the DB (some are compound). 
![screen shot 2018-08-06 at 3 18 22 pm](https://user-images.githubusercontent.com/1761268/43920760-d3f42644-9be7-11e8-9763-4cfe038fbe9a.png)
![screen shot 2018-08-06 at 3 18 08 pm](https://user-images.githubusercontent.com/1761268/43920763-d5b43316-9be7-11e8-8646-b0f83025d78d.png)
![screen shot 2018-08-06 at 3 28 51 pm](https://user-images.githubusercontent.com/1761268/43920767-d721e982-9be7-11e8-9d55-84612b2118d7.png)

**Comment by npaton** [comment]
All missing indexes were defined, but notall were created due to a loading order. A process now tries to enforce the index creation after waiting a little time after the app loads.
