### ISSUE TITLE
onGameStart onGameEnd onRoundStart

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#7]
I think we might want to have these additional two hooks in the config at the server side of the game. In particular:

- `onGameStart` is just renaming init (if it makes sense; I am thinking out loud here).
- `onGameEnd` could be a good place to convert the game score into dollar amounts etc. (
- `onRoundStart` at the beginning of the round. For example, when the round starts, I want to have something like: `player.round.set("alterIds", player.get("alterIds"));` to solve issue #24 .. although it can be done in other places such in between stages etc; it seems to me that at the start of the round is the most logical place.

**Comment by npaton** [comment]
All callbacks implemented:
* onGameStart
* onRoundStart
* onStageStart
* onStageEnd
* onRoundEnd
* onGameEnd

Needs testing.

**Comment by amaatouq** [comment]
Notes:
* `onGameStart` has `undefined` `game` object
* `onRoundStart` has `undefined` `game` object
* `onStageStart` is only called once per round and not at every stage (i.e., only the first stage of the round).

**Comment by npaton** [comment]
I see the onStageStart issue. Not the game `undefined` issues.

**Comment by amaatouq** [comment]
it returns a `Cursor` and not an object, right? (i.e., `game._id` is undefined, which was my test).

**Comment by npaton** [comment]
It does return the object, but no `game._id`. Adding.

**Comment by npaton** [comment]
That was correct, it was a cursor.
