### ISSUE TITLE
Assign player data prior to game init

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/empirica#71]
Related to issue #19 

I want to assign player data prior to game init, e.g. to let them pick an avatar, state a political party, or pick a username.

To do this, I modified `imports\core\ui\components\InstructionStep.jsx` and `...\Game.jsx` to pass the `player` object into the instruction steps components.

However, I then hit the error as per `augments.js`: 
`You called .get(...) or .set(...) but there is no data for the player yet. Did the game run for this player?`

Is there currently any way, or even a hack, to let me set player data prior to game init?

**Comment by npaton** [comment]
Yes, that is a change I've been wanting to make. I'm working on Empirica tomorrow, and I will try to get this into the main branch, I let you know.

**Comment by amaatouq** [comment]
Yes—to reiterate on Nicolas’s comment, we’ll add the Player object properly, which will allow to .get() and .set() values prior to the init() ..

**Comment by joshua-a-becker** [comment]
That's amazing, thank you!!!  Y'all are incredible.

**Comment by npaton** [comment]
You now get a `player` prop passed to instruction steps and you can use `get()` and `set()` as expected. Reopen if you have any issues. ⛵️

**Comment by joshua-a-becker** [comment]
and my game just magically works now.  amazing, thank you!!

**Comment by joshua-a-becker** [comment]
I spoke too soon---the player data set prior to game start seems to be erased once the game starts.

**Comment by npaton** [comment]
My apologies, yes, during game creation, the data field was overwritten. I pushed a fix, but I couldn't test it in a timely manner (in the middle of a major unrelated change, making things a bit messy to test locally for me at the moment), please let me know if the issue seems fixed for you.

Sorry about the ticket reopening, I'm reopening the ticket now, feel free to close if all good. Reopening is indeed not allowed if an admin closes the issue. From now on, I'll let reporters close their tickets once they've confirmed things working for them. ;)

**Comment by joshua-a-becker** [comment]
🎉🎉🎉 everything seems to be working fine.  🎉🎉🎉

**Comment by joshua-a-becker** [comment]
thanks i should have been able to test that myself.... 

the fact that it wasn't obvious means i'm doing something quasi-wrong.  i've added on a custom pre-lobby waiting page to synchronize simultaneous start for many players, and to keep people from being placed into a game who have walked away from the computer.  will share when its ready & battle tested.

it's currently pre-assignment (i now realize---its a mod of NoBatch.jsx with hijacking in the PublicContainer.jsx) but i think i should maybe build it into the instructions page so i can get database info on people in this state.

**Comment by joshua-a-becker** [comment]
i now realize that as an instructions page i wouldn't've had had to modify core at all and it will be way more share-friendly.  i think.
