### ISSUE TITLE
Archive Batches

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/empirica#72]
References Issue #20 :  Archiving treatments is really great.  Batches also tend to pile up in the workflow, especially during testing or when running a long sequence of trials.

Any plan to add archiving to batches?

**Comment by npaton** [comment]
Yes, it's something we definitely want to do. It's not at the top of the list at the moment since it doesn't break anything. But it should happen sooner rather than later. After our second beta probably.
