### ISSUE TITLE
Input Sanitization [Security]

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/empirica#73]
Posting this as an issue so the answer will be available for posterity.

Consider the likely scenario where there is a form input that gets stored directly in the database via `player.set()`   

Would y'all recommend sanitizing form input in any way to prevent against malicious users?    

Does meteor/empirica have anything like this built in?

**Comment by npaton** [comment]
Good question. This is not a final answer, but it should help for posterity and to build upon as you say.

The core of empirica does have a few things in place to avoid obvious security issues related to insecure input. Answering here for the usage of get/set, but overall we use the same techniques for all DB data.

The 2 main issues concerning user input are XSS (Cross-Site Scripting) and "SQL" injection.

For, XSS we do not sanitize values on input, any value can go all the way through to the DB. The protection happens at the React level, where values are sanitized at render time (no HTML is allowed at all). This is a common and valid practice.

For "SQL" injection (not actually an SQL issue here, we're using Mongo, but a similar potential vulnerability exists), all values are validated and are always nested into $set operations.

So we're doing the minimum vital to ensure protection from malevolent data input. We can always do better and more. I think we're doing what we should be, given our risks. But we are always interested if anyone has specific recommendations, or wants to further empirica's security.

One should note as well that we are not currently aiming at a very high level of data isolation, user data is transmitted to each player and there are no limits to what each client can update (within the limits of the `set()` methods). This was a choice made for convenience of experiment development. We would like to make data accessibility and updatability more configurable eventually. But, this is not to be confused with data integrity and potential attack vectors, which we already try to address, and should do our best to keep on top of. 🌊

**Comment by npaton** [comment]
With v2, the protections against XSS and SQL injections are still in place. We have also added new options to protect certain attributes (with protected, immutable, and private properties).

I don't see much more we can do. There is always a risk for the experiment developer to do the wrong thing and bypass React's safety measures. I don't know how to improve on this right now. We could add some documentation about best practices in React regarding security, though I don't think we'd have anything to add over all the literature about React already available. Also, the way React asks you to override its security is very explicit, and in any documentation about this, all the caveats will be mentioned.

So I think we are doing reasonably well in this regard at the moment (with v1 and v2), and I will close this ticket. If a new specific threat appears, please create a new issue, and we will immediately take a look at it. 🙌
