### ISSUE TITLE
New player button doesn't use playerIdParam

### ISSUE THREAD

**Issue by joshua-a-becker** [empiricaly/empirica#74]
Easy fix, but I'm not sure the best way to contribute.  For my local code, I added this variable to the `handleOpenAltPlayer` function in `Public.jsx` so that it is now:

```
handleOpenAltPlayer = event => {
    const { playerIdParam } = Meteor.settings.public;
	
    event.preventDefault();
    const randId = Math.random()
      .toString(36)
      .substring(2, 15);
    window.open(`/?`+playerIdParam+`=${randId}`, "_blank");
  };
```

**Comment by joshua-a-becker** [comment]
Upon usage, this solution _seems_ not to work.  Not totally sure yet if it's broken or if I've just been working too long---seems to not recognize distinct users across browser tabs.

**Comment by npaton** [comment]
Hey Joshua. I am not sure what you are trying to accomplish. The "New Player" button is meant to create a separate "browser context" for multiple players, during local testing. It replaces the need to open incognito windows and other browser windows to simulate multiple users while developing an experiment.

I'm not sure what integrating with `playerIdParam` solves. Typically, `playerIdParam` would only be used in production (locally during development it's more practical to just use the manual Identification page), while the "New Player" button would only be used in development (can be activated in prod with the `debug_newPlayer` setting, but as the name suggests, it's only for debugging). ;)

**Comment by joshua-a-becker** [comment]
I prefer to test everything in dev & staging exactly as it would be in production with as few changes as possible, so i use the same settings.json whenever possible in the final stages of development.

for anyone else coming along with this same goal, the additional fix can be found by editing `IdentifiedContainer.jsx` and changing line 10 to `const urlParams = new URLSearchParams(window.location.search);`

**Comment by joshua-a-becker** [comment]
also---though i haven't actually tested this in a while at this point---i suspect that a non-default playerIdParam would prevent staging & production testing with even manual new users in new browser tabs.  IMHO, it is a good design practice to always test the final production version with multiplayer games (where reelvant) before sending to mturkers.
