### ISSUE TITLE
Websocket failure with dev server in docker

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#93]
Hi @npaton, I'm running V2 in a container (this branch: https://github.com/Watts-Lab/deliberation-empirica/tree/dockerize) and binding port 3000 on the host to 3000 on the container. Empirica runs in the container, but when I access `localhost:3000` on the host (in either chrome or safari), I have this error:

![image](https://user-images.githubusercontent.com/4304478/166760718-9eadc550-9e2a-4c7f-b0d6-f200c8959761.png)

The page keeps refreshing indefinitely, sometimes it flickers, sometimes I see a little loading circle, and sometimes I get all the way to "no experiments available".

I can use the admin console, apparently like normal. I can also run the experiment as expected when I run it locally on the host - ie, not in a container.

**Comment by JamesPHoughton** [comment]
Also having some trouble running this on Elastic Beanstalk, not sure if it's related. There, logs show: 
```
empirica-prod_1  | [callbacks] callbacks: service token to connect to Tajriba is required (--token)
```

**Comment by yli12313** [comment]
<ins>**An Update on Fri. 5/6/22**</ins>:
- The issue of the local Empirica V2 deployment through a Docker container where the page was constantly refreshing was solved. the issue was that port **8844** had to be mapped locally to the container. Please see my attachment below as proof that the issue was resolved.
![image](https://user-images.githubusercontent.com/7104719/167207805-30656749-541d-4618-a9da-78b65b2d43d1.png)

However @npaton this is a very strange error right here. <ins>**How is that that when we deploy locally via Docker, we can access the Admin console no problem, but when we tried a cloud deployment to an Elastic Beanstalk Docker Environment, suddenly we have to login with a username and password**</ins>? The default username and password don't seem to work.

**Trying to access Admin console locally through a deployment on Docker (Working)**:
![image](https://user-images.githubusercontent.com/7104719/167208235-cb753805-0be8-40c8-94d0-395efd0591d7.png)

**Trying to access Admin console through an cloud deployment on an ELB Docker Environment (Not Working)**:
![image](https://user-images.githubusercontent.com/7104719/167208421-ed4b3530-4ec0-465f-a6f4-a9edcb5d0bc0.png)

**Comment by yli12313** [comment]
On, ELB we are also seeing high CPU Utilization.

![image](https://user-images.githubusercontent.com/7104719/167209054-90e5267d-3c2a-4fe6-b8ff-796394dd37a1.png)

#######

![image](https://user-images.githubusercontent.com/7104719/167209144-960f1372-cf69-401c-abb0-a84279904a10.png)

**Comment by JamesPHoughton** [comment]
CPU Usage for the same container on my local machine is around 2%, so not sure what's going on with EB.

**Comment by JamesPHoughton** [comment]
This morning @sumants-dev @rivera-lanasm and I set up an EB environment with a TCP port mapping 8844:8844 in addition to an HTTP port mapping 80:8844. This let us log in to the admin console on the EB deploy (still using the dev "empirica" command as in our [Dockerfile](https://github.com/Watts-Lab/deliberation-empirica/blob/dockerize/Dockerfile)). 

Here's the EB environment configuration:

![image](https://user-images.githubusercontent.com/4304478/167444400-074fe1a8-45b3-485a-a30a-2e9af0a3dc9c.png)
![image](https://user-images.githubusercontent.com/4304478/167444447-2b8a2948-2afd-49b6-9ac1-cdda9b56000e.png)


Still were not able to load the participant view - instead see this error there:
![image](https://user-images.githubusercontent.com/4304478/167443264-19f24e77-6407-42e4-a77a-f652079f0f86.png)

But we were able to log into the admin console! So, maybe the TCP port did something positive for the websockets? 

This error in the admin console looks like it may be a typo:
![image](https://user-images.githubusercontent.com/4304478/167444656-f5c57e13-4f77-40bd-88e9-f942205ba4f0.png)

Also saw these errors in the admin console: 
![image](https://user-images.githubusercontent.com/4304478/167444774-545c8d9c-983a-4885-b689-152737ffa10a.png)

When I tried to create a factor, saw this error:
![image](https://user-images.githubusercontent.com/4304478/167445128-9beb871d-a89a-48b6-8a2c-43ab9d17eae4.png)

The full server logs are here:
[BundleLogs-1652110478417.zip](https://github.com/empiricaly/empirica/files/8653160/BundleLogs-1652110478417.zip)


Still seeing high server utilization:
![image](https://user-images.githubusercontent.com/4304478/167445607-01eebc1a-d4b4-498f-9d2b-63d9314b6e49.png)

It may have something to do with this error from the logs, which looks like it's attempting and failing to run a callback every ~1 millisecond
```
empirica-prod_1  | [callbacks] [90m14:13:13.193 callbacks: service token to connect to Tajriba is required (--token)
empirica-prod_1  | [callbacks] [90m14:13:14.477 callbacks: service token to connect to Tajriba is required (--token)
empirica-prod_1  | [callbacks] [90m14:13:15.736 callbacks: service token to connect to Tajriba is required (--token)
empirica-prod_1  | [callbacks] [90m14:13:16.999 callbacks: service token to connect to Tajriba is required (--token)
empirica-prod_1  | [callbacks] [90m14:13:18.257 callbacks: service token to connect to Tajriba is required (--token)
```

**Comment by JamesPHoughton** [comment]
As an update, changing the GH action to include the .emprica directory in the zip package took care of the high server load and the Tajriba service token issue.
```yml
run: zip -r deploy-${{ steps.format-time.outputs.replaced }}.zip . -x "**node_modules**" -x '*.git*'
```
Still having trouble with the websocket.

**Comment by JamesPHoughton** [comment]
From my digging, it seems that to fix this (and allow us to run dev server on remote machines) need to add some code similar to:

```jsx
export function getURL() {
  const host = window.location.hostname;
  
  if (host === "localhost") {
    return "http://localhost:3000/query";
  }

  return "https://" + host + "/query";
}
```
into the empirica core source wherever there are currently hardcoded links to the localhost URL. For example, in [the callback for the admin login submit button](https://github.com/empiricaly/empirica/blob/906fcc1c5e2df0e35561576e21d2a787d59cea77/lib/admin-ui/src/components/SignIn.svelte#L18-L22), the funciton sends a URL to `Empirica.loginAdmin()` that it takes from [`/admin-ui/src/constants.js`](https://github.com/empiricaly/empirica/blob/906fcc1c5e2df0e35561576e21d2a787d59cea77/lib/admin-ui/src/constants.js):

```jsx
import { DEFAULT_TOKEN_KEY, URL } from "../constants";
...
const [admin, token] = await Empirica.loginAdmin(
        `${URL}/query`,
        username,
        password
      );
```
and `constants.js` has the URL hardcoded as localhost.
```js
export const URL = "http://localhost:3000";
```
This piece of code runs on the admin client, but isn't part of the experiment code, so needs to be modified in empirica core.

@npaton - is this something we can do (will we need to rebuild the project? I'm not very experienced with GoLang, would this be easy?) or is it better if I leave it for you?
