### ISSUE TITLE
Empirica Dev-Mode First Player Not Player

### ISSUE THREAD

**Issue by Alan-Qiao** [empiricaly/empirica#95]
In starting Empirica with docker on development mode, the first player (simulated by accessing localhost:3000) is not recognized as a player for an ongoing or newly started game.

#### Reproducing Conditions:
1. An image of deliberation-empirica exists locally
2. Development Server is ran using the command `docker-compose -f docker-compose-dev.yml up`
3. Access `http://localhost:3000`
4. The tab will always display Game Starting Screen

#### Current Work-around:
1. Create a new player

#### Supporting Images:
Initial State:
![image](https://user-images.githubusercontent.com/33496657/169871193-8f2222ad-da23-4bfd-bb57-cc473bede713.png)
![image](https://user-images.githubusercontent.com/33496657/169871306-3ef28c6b-0d16-421c-b25a-35b7eb8f885a.png)

After Starting New Game:
![image](https://user-images.githubusercontent.com/33496657/169871472-fb1e6621-bbf2-4cc6-9ab9-1638a0525f00.png)
![image](https://user-images.githubusercontent.com/33496657/169871604-2ce8cc05-9fa0-4a04-bb0f-5e193a9b5fef.png)

Creating a New Player:
![image](https://user-images.githubusercontent.com/33496657/169871685-d048c74a-999f-4bfc-adef-f5eb04b7a08a.png)

**Comment by Alan-Qiao** [comment]
@JamesPHoughton

From Summer 2022 Dev Team

**Comment by JamesPHoughton** [comment]
The docker container in this repository/commit is where we were experiencing this issue: https://github.com/Watts-Lab/deliberation-empirica/tree/53f17a159b5290fafb235822d39a316c600d0609

**Comment by npaton** [comment]
I suspect this is a problem with the localStorage in the browser. Try to clear your localStorage:

https://intercom.help/scoutpad/en/articles/3478364-how-to-clear-local-storage-of-web-browser

**Comment by npaton** [comment]
This should be fixed.
