### ISSUE TITLE
Empirca New Player Copies Old PlayerId

### ISSUE THREAD

**Issue by Alan-Qiao** [empiricaly/empirica#96]
On development mode, creating a new user from an existing user on localhost:3000 copies the entire url and appends a new playerId instead of replacing the playerId.

![image](https://user-images.githubusercontent.com/33496657/169872409-6a26c824-347b-40de-a493-a574213eebc7.png)
![image](https://user-images.githubusercontent.com/33496657/169872443-bcb3615c-0b90-4a82-91ac-ad49534f3b37.png)
![image](https://user-images.githubusercontent.com/33496657/169872480-00459c44-33c7-45e6-9c5b-68bcacf44bc8.png)

**Comment by Alan-Qiao** [comment]
@JamesPHoughton

From Summer 2022 Dev Team

**Comment by npaton** [comment]
This should be fixed in the latest release. Run `empirica upgrade`.
