### ISSUE TITLE
Export formatted data from V2 Admin or with linking script

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#98]
Is there a way to export data from the `tajriba.json` file yet? A script that just formats the data in an easier-to-understand way would be sufficient (and possibly preferred, so that we can include it in testing and in an automatic data extraction pipeline).

**Comment by npaton** [comment]
There is no export yet, it's coming soon.

**Comment by npaton** [comment]
Export was added with the `empirica export` command.
