### ISSUE TITLE
Fix callback URL to allow remote dev server

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#99]
Until we have a working prod server, it would be useful to be able to serve the dev server from a remote machine. 

At the moment, there are a number of places where the dev server hard-codes the service URL as `localhost`, which means that certain WebSockets break if we try to host from the cloud. To be able to host the dev server from a URL other than localhost, we need to add some code similar to:

```jsx
export function getURL() {
  const host = window.location.hostname;
  
  if (host === "localhost") {
    return "http://localhost:3000/query";
  }

  return "https://" + host + "/query";
}
```
into the empirica core source wherever there are currently hardcoded links to the localhost URL. For example, in [the callback for the admin login submit button](https://github.com/empiricaly/empirica/blob/906fcc1c5e2df0e35561576e21d2a787d59cea77/lib/admin-ui/src/components/SignIn.svelte#L18-L22), the funciton sends a URL to `Empirica.loginAdmin()` that it takes from [`/admin-ui/src/constants.js`](https://github.com/empiricaly/empirica/blob/906fcc1c5e2df0e35561576e21d2a787d59cea77/lib/admin-ui/src/constants.js):

```jsx
import { DEFAULT_TOKEN_KEY, URL } from "../constants";
...
const [admin, token] = await Empirica.loginAdmin(
        `${URL}/query`,
        username,
        password
      );
```
and `constants.js` has the URL hardcoded as localhost.
```js
export const URL = "http://localhost:3000";
```
This piece of code runs on the admin client, but isn't part of the experiment code, so needs to be modified in empirica core.

@npaton - is this something our team can do (will we need to rebuild the project? I'm not very experienced with GoLang, would this be easy?) or is it better if I leave it for you?

**Comment by npaton** [comment]
This should be fixed in the latest release. Run `empirica upgrade`.
